var pageses = [
    {
        "id": 1,
        "code": "001-00A",
        "title": "Page title 1",
        "subtitle": "Page subtitle 1",
        "metatitle": "Riure #1 · Lo Pati",
        "metadescription": "",
        "position": 1,
        "active": true,
        "text": "<h3>Superioridad Vs Inferioridad</h3>Uno de los efectos más impresionantes del acto de reír es el trastrocamiento de las relaciones jerárquicas que provoca. Muchas culturas han establecido periodos donde las distinciones de rango y estatus quedan suspendidas y el humor tiene vía libre para atacar instituciones hasta entonces intocables: las saturnales romanas, la fiesta de los rabiosos medievales y los carnavales son ejemplos de este momentáneo vuelco. El carácter fugaz y fulgurante de la carcajada fue intuido por Hobbes en su definición de humor como 'gloria súbita': <em>'se puede concluir que el humor no es sino la gloria súbita derivada de una concepción fugaz de eminencia en nosotros mismos, en comparación con la debilidad de los otros, o con nuestra propia de antes.'</em><br/><br/>El paso de la risa privada o canalizada desde el poder a la mueca revolucionaria no es ni mucho menos inmediato. Es enorme la distancia que va desde el cervantino <em>'Debajo de mi manto, al rey mato'</em> a matar el rey con toda las letras. Hay que admitir que una clase dominante puede convertirse ridícula mucho antes de convertirse en superflua en términos históricos. Desde la escandalosa caricatura de Luis Felipe I convirtiéndose en una pera hasta su abdicación debido a la Revolución de 1848 pasaron diecisiete años.<br/><br/>Northrop Frye definió la sátira como <em>'ironía militante'</em> y es este brazo armado del humor lo que puede tener unos efectos más devastadores en las relaciones de inferioridad / superioridad. En las antiguas sagas irlandesas el bardo era un soldado más, responsable de lanzar feroces burlas sobre el enemigo. Estas burlas podían llegar a ejercer un efecto físico a distancia sobre el objeto de la risa (llenándole, por ejemplo, el cuerpo de llagas). En sus orígenes mitológicos del humor es confunde, pues, con la magia y la maldición. De hecho, en irlandés la palabra 'risa' (<em>tibiu</em>) también significa 'golpear'.<br/><br/>El humor se mueve siempre entre dos extremos: la bufonada y la sátira trágica. La bufonada se nutre del lado ridículo de la naturaleza humana, a menudo de nuestra inescapable limitación física: resbalones, tartamudeos, accidentes y deformidades. Su base es degradar el objeto de la risa y hacernos pensar que, al menos por una vez, no somos nosotros los que hemos metido la pata. La sátira trágica apunta más arriba y fila delgado. Es un tipo de humor que provoca la risa pero no participa de él porque el autor está demasiado horrorizado por la corrupción generalizada que le rodea. <em>'Ira te lacrimae'</em> promete Juvenal a los decadentes nobles de la Roma imperial en su primera sátira. Karl Kraus, dominador de este género en el siglo XX, afirmó que 'si una sátira es entendida por el censor es que merece ser censurada'. Sin embargo, no necesariamente es la sátira más elaborada la que acaba teniendo una mayor efectividad. <em>'El grito de Iowa'</em>, repetido hasta la extenuación por los medios audiovisuales, puso fin a la carrera del candidato demócrata Howard Dean.<br/><br/>La repetición está en la base de un fenómeno puramente contemporáneo: la memificación. Etimológicamente la palabra 'sátira' está emparentada con 'saturación' y cualquier usuario de Youtube puede certificar que un fragmento corto, descontextualizado y repetido hasta la saturación ejerce un hipnótico e infeccioso efecto. Se trata del paroxismo de una tendencia que se inició con la invención de medios de reproducción mecánica como la litografía y la imprenta Estas técnicas sacaron el humor político de los salones y la acercaron a las masas bajo la forma de caricaturas y aucas.<br/><br/>En el humor contemporáneo se ha producido el surgimiento de fenómenos nuevos como el hacktivismo, el desasimiento de páginas web o la suplantación de personalidad pero el principio subyacente sigue siendo la inversión momentánea de las relaciones de poder y jerarquía. Durante los momentos de gloria repentina de una carcajada atisban un mundo donde las relaciones de superioridad / inferioridad han quedado abolidas.<br/><br/>Xavier Zambrano.<br/><br/>",
        "summary": "<h3>Superioridad Vs Inferioridad</h3>Uno de los efectos más impresionantes del acto de reír es el trastrocamiento de las relaciones jerárquicas que provoca. Muchas culturas han establecido periodos donde las distinciones de rango y estatus quedan suspendidas y el humor tiene vía libre para atacar instituciones hasta entonces intocables: las saturnales romanas, la fiesta de los rabiosos medievales y los carnavales son ejemplos de este momentáneo vuelco. El carácter fugaz y fulgurante de la carcajada fue intuido por Hobbes en su definición de humor como 'gloria súbita': <em>'se puede concluir que el humor no es sino la gloria súbita derivada de una concepción fugaz de eminencia en nosotros mismos, en comparación con la debilidad de los otros, o con nuestra propia de antes.'</em><br/><br/>Xavier Zambrano.<br/><br/>",
        "medias": [
            {
                "id": 1,
                "title": "Luís Felipe I convirtiéndose en una pera",
                "author": "Charles Philipon",
                "location": "",
                "year": 1831,
                "text": "Este boceto fue dibujado en 1831 por el caricaturista Charles Philipon ante un tribunal. En el proceso se arriesgaba a una condena de 5 años por los dibujos que había publicado en la revista <em>La Caricature</em>. 'Todo puede parecerse a un rey' - fue su alegato de defensa - 'y si condenamos el primer dibujo, también hay que condenar el último y todos los dibujos de peras'. Con Philipon el arte de la caricatura deja de cebarse en la deformidad de los humildes y se convierte en una potente herramienta de crítica política, la punta de lanza de la libertad de prensa.",
                "image": "1.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 2,
                "title": "El Auca de los pelegrinos",
                "author": "La Campana de Gràcia",
                "location": "",
                "year": 1891,
                "text": "Las primeras aucas trataban temas bastante inocuos y no se caracterizaban por su humor: inventarios de artes y oficios, de juegos de infancia o de fiestas del año. En el siglo XIX, sin embargo, la ampliación temática coincidió con la eclosión de su popularidad. <em>El Auca de los peregrinos</em> es paradigmática de la corriente anticlerical y la agitación social del cambio de siglo. Se siguieron usando aleluyas con fines satíricos y propagandistas hasta la Guerra Civil, momento donde encontramos publicaciones como <em>El Auca del pequeño burgués que parece mucho y no es nada.</em>.",
                "image": "2.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "2.png",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega imatge",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 3,
                "title": "Viaje promocional al infierno",
                "author": "Karl Kraus",
                "location": "",
                "year": 1921,
                "text": "Karl Kraus fue el más grande practicante moderno de la sátira impulsada por la indignación moral ante la corrupción generalizada. Desde su revista <em>Die Fackel</em> fustigó la bienpensante sociedad vienesa de entreguerras. Intuyó con gran clarividencia la capacidad de la publicidad para banalizarlo todo, incluso el horror más extremo. A <em>Viaje promocional al infierno</em> atacó las empresas que organizaban excursiones turísticas a los campo de batalla más sanguinarios de la 1ª Guerra Mundial: “Recibiréis impresiones inolvidables de un mundo donde no queda ni un centímetro cuadrado que no haya sido destrozado por las granadas y los anuncios”.",
                "image": "3.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "3a.pdf",
                "attachment2": "3b.pdf",
                "attachment3": "",
                "textattachmentbutton": "descarrega article alemany",
                "textattachmentbutton2": "descarrega traducció anglès",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 4,
                "title": "Veteranos de guerras futuras",
                "author": "Estudiantes de Princeton",
                "location": "",
                "year": 1936,
                "text": "El 1936 un grupo de estudiantes de la Universidad de Princeton, viendo muy cercana la posibilidad de otra guerra mundial, pidieron cobrar por anticipado la pensión que los correspondería en un futuro como veteranos de guerra. De este modo, podrían disfrutar el dinero mientras todavía eran jóvenes y no tener que esperar a estar estropeados por las bombas. Esta fina sátira de la resignación colectiva ante el militarismo tuvo un gran impacto y aconteció profética cuando la mayoría de integrantes del movimiento fueron llamados a filas.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/JnE9pDPqTKE?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 5,
                "title": "Mon oncle",
                "author": "Jacques Tati",
                "location": "",
                "year": 1958,
                "text": "Jacques Tati desterró de sus películas el humor tradicional basado en la comicidad de los personajes. El suyo es un humor de la observación: planos generales sostenidos en el tiempo que permiten al espectador hacerse cómplice del la comicidad del cotidiano. Toda situación largamente observada acontece un gag. A la broma pesada de los niños de <em>Mi tío</em>, sitúa la cámara entre los niños, convirtiendo el espectador en un perpetrador y apuntando a una comicidad muy contemporánea: la cámara oculta. El factor repetición anticipa el humor basado en accidentes y bromas pesadas de la era de Internet.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/pE5vm8vTWCI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 6,
                "title": "El regreso de la columna Durruti",
                "author": "Internacional Situacionista / André Bertrand",
                "location": "",
                "year": 1967,
                "text": "<em>Le Retour de la Colonne Durutti</em> fue un cómic/panfleto repartido entre los estudiantes de la Universidad de Estrasburgo. Está construido mediante la técnica del détournement: apropiarse de medios y canales de la sociedad del espectáculo, manipularlos y usarlos como herramienta de combate contra esta misma sociedad. La obra combina dibujos, fotogramas, anuncios y fragmentos de libros, retocados para abrirlos a nuevos significados. El humor situacionista combina registros dispares, pasa de la ultra intelectualización a la grosería en una misma viñeta, y reivindica la fuerza del texto en una sociedad que empezaba a estar saturada de estímulos visuales.",
                "image": "6.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "6.pdf",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega pamflet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 7,
                "title": "Why I Want to Fuck Ronald Reagan",
                "author": "J.G. Ballard",
                "location": "",
                "year": 1980,
                "text": "A la convención republicana de 1980, que proclamaría Ronald Reagan como candidato presidencial, un grupo de situacionistas repartió entre los delegados un folleto que contenía un texto de J.G. Ballard de 1967. El texto estaba presentado como si fuera un informe interno del propio partido e incluso llevaba el sello oficial. En su demoledora sátira de los estudios de opinión, Ballard ataca una política basada en la primacía de imágenes vacías. Tanta banalidad era muy capaz de traer al país a escoger un mediocre actor de serie B como presidente. Ballard anticipó este hecho 13 años antes de que se produjera, cuando Reagan era sólo gobernador de California, en un texto que parodia con un lenguaje pseudo científico el masoquismo de las masas de votantes.",
                "image": "7.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "7b.jpg",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega fullet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 8,
                "title": "Barbie Liberation Organization",
                "author": "RTMark",
                "location": "",
                "year": 1993,
                "text": "El grupo RTMark compró en 1993 centenares de muñecas Barbies y muñecos G.I. Joe. Intercambiaron las grabaciones internas de voz de los dos juguetes y las devolvieron a los estantes de las tiendas. Las niñas se encontraron, pues, con muñecas Barbies que decían “fuego a discreción” y los niños con G.I. Joes que decían “quiero ir de compras”. Esta acción contra los estereotipos de género en los objetos producidos por la sociedad del consumo es de clara inspiración situacionista. El hackeo de objetos tecnológicos acontece un nuevo y potente canal para la sátira: es el nacimiento del hacktivismo.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/OPeOD4ZQdXY?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 9,
                "title": "The Yes Men y la Organización Mundial de Comercio",
                "author": "The Yes Men",
                "location": "",
                "year": 1999,
                "text": "Empezando con una simple web falsa que quería pasar por la de la Organización Mundial del Comercio, los Yes Men consiguieron ser invitados como conferenciantes a prestigiosas conferencias y encuentros de sectores neoliberales. Fueron entrevistados por canales como la CNBC o la BBC, donde expresaron sin tapujos opiniones como por ejemplo que había que electrocutar los trabajadores poco productivos. Esta brillante sátira de las élites económicas y la complicidad con que cuentan por parte de los medios de comunicación situó la suplantación de personalidad como técnica humorística contemporánea, en una tendencia que después seguirían humoristas como Sacha Baron Cohen.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/sW35PKEVYMw?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 10,
                "title": "Una noche con Amenábar",
                "author": "Querido Antonio",
                "location": "",
                "year": 2006,
                "text": "La sátira de un personaje público es uno de los géneros que más memes produce. La exposición a los medios comerciales obliga a las personalidades a adoptar una pose y su tendencia a la autopromoción los convierte en un blanco ideal para las sátiras. En este vídeo de Alberto González Vázquez, el director de cine Amenábar es parodiado en una sucesión de escenas llenas de alusiones a géneros fílmicos. En la sátira contemporánea el contexto a menudo es visual y un vídeo no se explica sin otros muchos vídeos en una cadena de referencialidades sin fin.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/zH1KxoYp2b4?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 11,
                "title": "El político neoliberal",
                "author": "Pony Bravo",
                "location": "",
                "year": 2013,
                "text": "La inclusión de un personaje ficticio en imágenes documentales es una técnica de gran recorrido humorístico desde <em>Zelig</em> de Woody Allen. Este videoclip del grupo Pony Bravo no busca el equívoco (el retoque es deliberadamente evidente) sino la incongruencia y la denuncia de unas élites que siempre nos ofrecen la cara edulcorada por los medios.",
                "image": "",
                "youtube": "",
                "vimeo": "http://player.vimeo.com/video/60601830?title=0&amp;byline=0&amp;portrait=0",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 11,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            }
        ]
    },
    {
        "id": 2,
        "code": "001-00B",
        "title": "Page title 2",
        "subtitle": "Page subtitle 2",
        "metatitle": "Riure #2 · Lo Pati",
        "metadescription": "",
        "position": 2,
        "active": true,
        "text": "<h3>INCONGRUENCIA</h3> Según los partidarios de esta teoría, la esencia del humor se situaría en lo incongruente, en la confluencia en un mismo punto de dos ideas o marcos de referencia alejados y dispares. La incongruencia humorística linda por un extremo con la ironía (cuando pasado el impacto inicial somos capaces de reconciliar las dos ideas y darnos cuenta de que no estaban tan alejadas) y, por el otro, con el absurdo (cuando todo intento de reconciliación resulta inútil). Bergson sostiene que “una situación es cómica cuando pertenece simultáneamente a dos series de acontecimientos totalmente independientes y es susceptible de ser interpretada según dos significados completamente distintos al mismo tiempo”.<br><br>La frustración de expectativas juega un papel importante en el sentimiento de incongruencia. Pascal afirma que “nada nos hace reír tanto como una disparidad sorprendente entre lo que esperábamos y lo que vemos”. Ante una situación incongruente nos sentimos durante unos instantes, hasta que la risotada acude a nuestro rescate, víctimas de un hábil estafador, como si la existencia se mofara de nuestras expectativas más sólidas. Kant sitúa el arranque de la risa en el momento en que “una tensa expectativa se disuelve en la nada”.<br><br>La imagen incongruente es un híbrido que participa de la naturaleza, curiosa y a la vez amenazante, de la quimera. La quimera (cabeza de león, cuerpo de cabra, cola de dragón) nace en la mitología griega como ser fatídico, portador de terribles desgracias. Aristóteles afirmaba que los animales, a diferencia de los animales, son incapaces de reír. Las quimeras, al abolir la separación entre especies animales, nos generan profundas inquietudes sobre las fronteras de nuestro propio cuerpo y la línea de separación entre lo humano y lo animal. El arte griego era ajeno a los efectos humorísticos de la incongruencia, pero no a su potencia simbólica. La figura del Hermafrodita y del Afroditus o Afrodita masculina fue venerada en cultos mistéricos alejados de la religión oficial. Los romanos también evitaban la incongruencia y se mostraban más tendientes a la sátira. Horacio advirtió que el pintor que plantara un cabeza humana a un cuerpo de caballo sin duda provocaría una reacción humorística, pero debería limitar-se a enseñar la pieza “de modo privado”.<br><br>Fue en la era medieval cuando la fascinación por las quimeras, gárgolas y babuinos estalló en los capiteles y en las glosas marginales de manuscritos en forma de ilustraciones escatológicas y abiertamente sexuales que desestabilizaban los márgenes de los textos de salterios y breviarios: se produce una incongruencia entre los discursos profanos y sacro, entre el cuerpo del texto y la glosa, que nos remite a la heteroglosia que Bajtin detectó como definitoria de aquel período.<br><br>Un objeto o situación incongruente se sitúa siempre en el umbral entre lo humorístico y lo horrible o macabro. Por ello, las imágenes incongruentes fueron recurrentes en los surrealistas. André Breton describe el efecto de la imagen surrealista en términos de incongruencia: “la maravillosa facultad de reunir, sin abandonar el reino de la experiencia, dos realidades muy alejadas; y hacer saltar la chispa al ponerlas en contacto”.<br><br>Bergson apuntó que una de las situaciones humorísticas más frecuentes se da cuando vemos que una persona se convierte o es tratada como una cosa. El cine mudo exploró la vis cómica de nuestro cuerpo hasta el punto de agotar la posible combinatoria de caídas y persecuciones. Quizá la fascinación que nos despiertan las imágenes y las situaciones incongruentes se deba, como ha apuntado Peter Berger, a una incongruencia consustancial a nuestra propia naturaleza, una incongruencia “existencial” derivada del hecho de ser al mismo tiempo cuerpos/cosas y personas.",
        "summary": "<h3>INCONGRUENCIA</h3> Según los partidarios de esta teoría, la esencia del humor se situaría en lo incongruente, en la confluencia en un mismo punto de dos ideas o marcos de referencia alejados y dispares. La incongruencia humorística linda por un extremo con la ironía (cuando pasado el impacto inicial somos capaces de reconciliar las dos ideas y darnos cuenta de que no estaban tan alejadas) y, por el otro, con el absurdo (cuando todo intento de reconciliación resulta inútil). Bergson sostiene que “una situación es cómica cuando pertenece simultáneamente a dos series de acontecimientos totalmente independientes y es susceptible de ser interpretada según dos significados completamente distintos al mismo tiempo”. ",
        "medias": [
            {
                "id": 12,
                "title": "Voeux du paon",
                "author": "Anónimo",
                "location": "Pierpont Morgan Library",
                "year":  "ca. 1350",
                "text": "La Edad Media a menudo se ha presentado como una época en la cual el oscurantismo feudal y religioso imponía un rictus serio a todas las manifestaciones culturales. Sin embargo, en los márgenes de los manuscritos y en los capiteles de las catedrales es detectable una marcada predilección por la risotada subversiva, por la confrontación y confusión de discursos, que se plasmó en forma de gárgolas y quimeras imposibles. La iluminación de los manuscritos, tarea encargada habitualmente a una persona distinta del escriba que fijaba del texto, fue un terreno propicio para el estallido incontinente de este gusto por la risotada: el margen se convirtió en comentario desestabilizador de la seriedad oficial, la nota dejó de ser acotación para convertir-se en un estilete que abría una vía de agua por donde se vaciaba la pomposidad de los grandes discursos monolíticos. En esta ilustración al margen de un romance que conoció una gran difusión, un hombre desnudo se burla de la galante escena cortesana. Más abajo, una quimera serpentina tocada con una mitra ridiculiza la religión. Los dos grandes discursos idealistas medievales, el caballeresco y el religioso, son atacados en una misma glosa marginal desde la carnalidad y animalidad más grosera.",
                "image": "12.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 13,
                "title": "Ressemblances humaines et animales",
                "author": "Charles Le Brun",
                "location": "",
                "year": 1690,
                "text": "Resulta curioso que uno de los artífices del gusto neoclásico en pintura, el pintor y tratadista, Charles Le Brun, fuera al mismo tiempo el autor de una de las series de dibujos más inquietantemente humorísticas de la historia del arte. Compendio exhaustivo de todas las posibles semblanzas fisonómicas entre las personas y las bestias, <em>Ressemblances humaines et animales</em> se convierte en un homenaje a nuestra naturaleza hibrida. Decía Aristóteles que el sur humano es el único animal que ríe. Podríamos redondear la definición añadiendo que es el único animal que se avergüenza y oculta las manifestaciones de su propia animalidad. Los dibujos de Le Brun nos inquietan porque recorren el camino inverso al de las fábulas moralizantes (que humanizan a los animales) y nos remiten a una involución atávica, una transformación animal explorada por la mitología griega, en múltiples variantes, desde que los marineros de Ulises fueron convertidos en cerdos.",
                "image": "13final.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 14,
                "title": "Mlle des Faveurs a la Promenade a Londres",
                "author": "Anónimo",
                "location": "British Museum",
                "year": "1770-1780",
                "text": "La figura del extranjero siempre ha sido un agente provocador de situaciones incongruentes. El choque entre los usos y maneras de uno y otro país es fuente de ridículas incomprensiones. Todos los países cuentan con chistes ajustados al célebre patrón de “se encuentran en un bar un español, un francés y un alemán...”. La lengua inglesa ha fijado esta incongruencia consustancial a la condición de extranjero en el adjetivo <em>“outlandish”</em> (out+land), que suele aplicarse a situaciones, comentarios y bromas de una incongruencia <em>bizarre</em>. En este grabado satírico la <em>coiffure à physionomie élevée</em> que se estilaba en la Francia cortesana es confundida por un palomar en Inglaterra. Con todo, la dinámica del grabado no se limita al choque de modas, apunta también aun choque entre el temperamento aristocrático francés y la mentalidad británica. Su fecha de publicación, pocos años antes de la Revolución Francesa, es también significativa: una clase social se convierte en ridícula antes de convertirse en superflua en términos históricos.",
                "image": "14.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 15,
                "title": "Fatty, Mabel and the Law",
                "author": "Mabel Normand",
                "location": "",
                "year": 1912,
                "text": "El humor de las <em>slapstick comedies</em> del cine mudo se basaba en una gestualidad aparatosa, unas persecuciones frenéticas y el colapso de cualquier elemento constructivo que ofreciera el más mínimo punto de apoyo. Todas esta constantes ponían de relieve las penurias que nos acarrea tener un cuerpo sujeto —además de a sus propias leyes— a la ley de la gravedad. Una de las tipologías clásicas de este género son las escenas <em>don’t kiss me</em>. La actriz cómica Mabel Normand sobresalía en este tipo de escenas físicas, abofeteando sin clemencia a los hombres que intentaban robarle un beso. La incongruencia entre unos hombres sentimentales, infantiles y gordinflones y las iracundas reacciones de la menuda Mabel invertían las relaciones de poder entre sexos y la convirtieron en la antítesis de otras actrices de cine mudo más melindrosas como Mary Pickford.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/eq-hlPRnS1c?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 16,
                "title": "L.H.O.O.Q.",
                "author": "Marcel Duchamp",
                "location": "",
                "year": 1919,
                "text": "En uno de los gestos fundacionales del arte moderno, Duchamp añadió bigote y perilla a una postal de la Gioconda. Tituló la obra resultante <em>L.H.O.O.Q.</em>, iniciales que pronunciadas en francés suenan como <em>“elle a chaud au cul”</em>. Uno de los adjetivos preferidos de Duchamp para descalificar a movimientos que no le gustaban era tildarlos de aburridos, adjetivo que dedicó por ejemplo al cubismo. El humor dadaísta busca la incongruencia entre el discurso solemne del arte oficial, basado en etéreas nociones de sublimidad, y los retoques burlones que desestabilizan la pieza y la llevan a un contexto ordinario. Con un sutil retoque o un simple cambio de contexto el <em>ready-made</em> eleva objetos cotidianos a la categoría de arte. En el caso de esta pieza, las infinitas reproducciones mecánicas en forma de postal se habían encargado de degradar la imagen de la Gioconda hasta convertirla en ordinaria, familiar, demasiado “aburrida”.",
                "image": "16.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 17,
                "title": "Ministry of Silly Walks",
                "author": "Monty Python",
                "location": "",
                "year": 1970,
                "text": "Emitido por la BBC entre 1969 y 1977, el programa de gags <em>Monty Python's Flying Circus</em> revolucionó el formato televisivo de los programas de humor y derrumbó para siempre la concepción tradicional que lo que se entendía por “humor británico”. El carácter imprevisible de su humor conseguía una incongruencia radical entre gags: durante el curso de una emisión se sucedían gags irónicos con otros de tipo sarcástico, escatológico o intelectual. A menudo, la incongruencia entre distintas formas de humor se daba dentro de un mismo gag. El espectador quedaba desarmado, incapaz de anticipar el siguiente golpe. En este gag, se nos presenta el Ministerio de maneras absurdas de andar. Con guiños a la gestualidad del cine mudo, el gag resulta a la vez absurdo y finamente satírico de los delirantes requisitos para la concesión de ayudas gubernamentales.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/iV2ViNJFZC8?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 18,
                "title": "Ludwig van Beethoven",
                "author": "John Belushi (Saturday Night Live)",
                "location": "",
                "year": 1977,
                "text": "John Belushi, cómico y miembro de <em>The Blues Brothers</em>, marcó un hito en el humor televisivo con sus apariciones en el programa <em>Saturday Night Live</em> de la NBC entre 1975 y 1979. Sus salvajes gags en directo popularizaron el personaje del samurai Futaba, un guerrero oriental que se presentaba fuera de contexto, ejerciendo profesiones tan dispares como la de botones de hotel, psiquiatra, reparador de televisores o optometrista. El consumo de drogas que él y su compañero de banda Dan Aykroyd realizaban antes, durante y después del show adquirió dimensiones legendarias y acabó segando su vida a los 33 años. En este gag, se apunta a la transformación de la personalidad mediante la intervención de sustancias: un lánguido Beethoven se convierte de repente en Ray Charles. Es una transformación con ecos de El Dr. Jekyll y Mr. Hyde y de la incongruencia primordial: la convivencia no siempre pacífica de distintas personalidades dentro de cada persona.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/9YjQ9OmneMI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 19,
                "title": "Tarzan",
                "author": "Rémi Gaillard",
                "location": "",
                "year": 2009,
                "text": "Rémi Gaillard se ha convertido en el bromista por excelencia de la era Youtube. Sus travesuras le han granjeado millones de seguidores y diversas condenas judiciales. El bromista que tira del hilo de la bromas hasta sus últimas consecuencias es, como los psicóticos, perfectamente coherente dentro de su marco referencial. El problema es que su marco y la realidad son perfectamente incongruentes. Así, Gaillard ve un laberinto de Pac-Man en los pasillos de un supermercado o una trinchera militar en las trampas de arena de un campo de golf (haciendo honor al origen de su nombre: búnker) . En el video <em>Tarzan</em>, reclama y ocupa un espacio perfectamente artificial e incongruente: el zoológico urbano. ¿Hacerse incongruente en un espacio incongruente no será tal vez la más congruente de las acciones?",
                "image": "",
                "youtube": "http://www.youtube.com/embed/M-g-etgFk80?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 20,
                "title": "Island of da motherboard slaughter",
                "author": "Gangpol & Mit",
                "location": "",
                "year": 2009,
                "text": "En los últimos años, en el campo de la animación y el cómic, se ha producido una corriente estética que aúna la inocencia formal más naíf y el trasfondo temático más <em>hardcore</em>. El efecto de esta incongruencia forma/fondo puede ser explotado tanto para fines trágicos como cómicos. El dueto gráfico y musical Gangpol & Mit usa el <em>pixel-art</em>, las perspectivas isométricas herederas de los videojuegos y los sonidos MIDI para crear extrañas e hipnóticas animaciones que tienen algo de trance chamánico. Mutilaciones, canibalismo y máscaras primitivas son endulzadas por la inocencia del píxel y los sonidos puros de los bips-bips digitales.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/FL5w5pj_5JA?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 21,
                "title": "Drunken politicians",
                "author": "Reactor2studio",
                "location": "",
                "year": 2013,
                "text": "Decía Groucho Marx que la política es el arte de buscar problemas, encontrarlos, hacer un diagnóstico falso y aplicar después los remedios equivocados. Pura incongruencia con las nobles cantinelas del bien común y el servicio público. Cuando un político se muestra borracho en un contexto cargado de solemnidad y cálculo, como un parlamento, el efecto cómico es inmediato e infeccioso. En un mitin, por el contrario, el efecto no es tan fuerte porque se trata de ceremonias ya concebidas originariamente para aturdir los sentidos y anular el raciocinio, auténticas borracheras colectivas.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/kTy5JaH06zI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 22,
                "title": "A Blobs Bike Ride",
                "author": "Jaimie Warren",
                "location": "",
                "year": 2013,
                "text": "En esta pieza de la artista norteamericana Jaimie Warren, una recreación de <em>Le déjeuner sur l'herbe</em> se convierte en una apoteosis del mal gusto, un grosero picnic donde los tonos pastel compiten con los chillidos más estridentes y las canciones más insufribles hasta alcanzar la incongruencia plástica total. El resultado de esta suerte de wagnerianismo inverso no puede ser otro que una digestión pesada. Uno de los efectos cómicos más recurrentes consiste en hacer aflorar las sonoridades y olores de nuestra animalidad en un contexto extemporáneo. Así, los pedos y eructos en momentos inconvenientes se convierten en recordatorios que nos advierten que por nuestras entrañas no corren tan sólo pensamientos sublimes.",
                "image": "",
                "youtube": "",
                "vimeo": "http://player.vimeo.com/video/68719482?title=0&amp;byline=0&amp;portrait=0",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 11,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            }
        ]
    },
    {
        "id": 3,
        "code": "001-00C",
        "title": "Page title 3",
        "subtitle": "Page subtitle 3",
        "metatitle": "Riure #3 · Lo Pati",
        "metadescription": "",
        "position": 3,
        "active": true,
        "text": "<h3>MATAR AL CENSOR</h3> Existen dos tipos de censores: un censor interno formado por miedos atávicos y tabúes íntimos, y un censor externo, suma de todas las convenciones implícitas en las relaciones sociales y la moral establecida. Según Freud, el humor tiene su origen en una tendencia agresiva contra estos dos censores que están conectados y se retroalimentan. La energía psíquica que antes se requería para reprimir la agresividad se libera en el momento de la carcajada. La liberación de la represión y la momentánea libertad de pensamiento proporcionan la descarga placentera que produce el humor. En la proliferación de chistes cínicos sobre el matrimonio y la religión, Freud detectó una <em>agresividad velada</em> contra las exigencias de la moral social. El humor negro, con su fijación contra lo demasiado sacralizado, se convierte así en lo contrario del tacto y la corrección política.<br><br>André Breton, en el prólogo a su <em>Antología del humor negro</em>, rebasó las categorías freudianas y situó el humor negro como \"el enemigo mortal del sentimentalismo\", una actitud que lleva el desenfreno hasta el borde mismo de la nada. En sus exploraciones de los temas de la muerte, la violencia, la deformidad y el sexo, los surrealistas combatieron un arte oficial que pasaba de puntillas cada vez que se encontraba ante una temática escabrosa. El humor negro busca un efecto de <em>placer culpable</em>: una broma que simultáneamente nos divierte y nos repele provoca un choque y una oscilación inestable entre estas dos reacciones.<br><br>Según Bergson, una persona aislada no experimentaría reacciones humorísticas, ya que el humor precisa de un <em>eco</em> en los otros. En una ocasión, Kierkegaard pregunto a un amigo: \"¿tú de verdad te ríes cuando estás solo?\". En nuestra era las redes sociales se han convertido en altavoces amplificadores de esta resonancia social que parece buscar el humor negro. Las salvajes bromas en Twitter o en los grupos de Whatsapp sobre el asesinato de las niñas de Alcàsser o la mutilación de Irene Villa en atentado terrorista han terminado dando forma a un género de humor típicamente postmoderno. ¿Exploración de las cicatrices en el inconsciente colectivo o venganza contra el bombardeo informativo con que los medios de masas se regodean en los sucesos más morbosos de la actualidad?<br><br>Los chistes racistas o machistas, según Ronald de Sousa, participan de una <em>ética negativa</em>. Al situar en un contexto lúdico afirmaciones que en otro contexto serían inaceptables, estos chistes <em>relajan</em> al censor moral del oyente y se convierten en un vehículo de perpetuación de prejuicios y estereotipos. Sin embargo, el humor negro, en sus manifestaciones más sutiles, se erige en un potente instrumento artístico. Hablamos de aquellos casos en los cuales el humor se atreve a murmurar lo indecible en lugar de vociferar los tópicos más reaccionarios. El humor negro se convierte así en la bilis negra de la melancolía; en vez de atacar a los otros, hurga en nuestra caducidad y fragilidad. En el condenado a muerte que gasta una broma al verdugo el día de su ejecución, Freud apreció una dignidad muy superior a la del chiste estereotipado.",
        "summary": "<h3>MATAR AL CENSOR</h3> Existen dos tipos de censores: un censor interno formado por miedos atávicos y tabúes íntimos, y un censor externo, suma de todas las convenciones implícitas en las relaciones sociales y la moral establecida. Según Freud, el humor tiene su origen en una tendencia agresiva contra estos dos censores que están conectados y se retroalimentan. La energía psíquica que antes se requería para reprimir la agresividad se libera en el momento de la carcajada. La liberación de la represión y la momentánea libertad de pensamiento proporcionan la descarga placentera que produce el humor. En la proliferación de chistes cínicos sobre el matrimonio y la religión, Freud detectó una <em>agresividad velada</em> contra las exigencias de la moral social. El humor negro, con su fijación contra lo demasiado sacralizado, se convierte así en lo contrario del tacto y la corrección política.",
        "medias": [
            {
                "id": 23,
                "title": "A modest proposal",
                "author": "Jonathan Swift",
                "location": "",
                "year": 1729,
                "text": "Este recorrido por algunos de los hitos históricos del humor más oscuro se abre con el autor irlandés en un homenaje a la idéntica posición inaugural que ocupa en la <em>Antología del humor negro</em> de Breton. En su <em>Modesta proposición</em> Swift argumenta que la mejor solución a los problemas endémicos de sobrepoblación y pobreza en Irlanda sería que los pobres vendieran sus hijos como alimento para los ricos. El contraste entre el salvaje contenido de la sátira y su tono de informe técnico acaba erigiendo una potente denuncia de las actitudes condescendientes y moralistas sobre la pobreza. Muchos lectores no entendieron la ironía del panfleto: las mismas personas que se escandalizaban ante la perspectiva de que los niños fueran devorados no perdían horas de sueño cuando esos mismos niños morían de hambre. Swift fue declarado \"mentalmente inestable\" por un comité médico tres años antes de morir. En la lectura de su testamento se produjo su última broma a título póstumo. Haciendo honor a lo que había advertido en unos versos escritos hacía décadas y considerados satíricos en su momento, se descubrió que había legado la mayor parte de su fortuna para la construcción de un manicomio.",
                "image": "23.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 24,
                "title": "La dame ovale",
                "author": "Leonora Carrington",
                "location": "",
                "year": 1939,
                "text": "La pintora y prosista anglomexicana exploró en sus obras los rincones más turbios de la psique hasta vislumbrar la lucidez que se encuentra \"allá abajo\", al fondo de las simas de la sexualidad y la locura. Breton se maravilló ante \"la luz oculta\" que satura sus obras. El libro de relatos surrealistas <em>La dame ovale</em> conjura poderosas imágenes sobre las máscaras de la personalidad y lo hace con un tono juguetón que remite a los cuentos más perturbadores de los hermanos Grimm y a las monstruosas criaturas de Swift. Las ilustraciones de Max Ernst terminan de redondear un libro-objecto que se convirtió en uno de los artefactos más inquietantes del movimiento surrealista.",
                "image": "24.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 25,
                "title": "Monólogos",
                "author": "Lenny Bruce",
                "location": "Floruit",
                "year": "1950-1966",
                "text": "El llamado \"Charlie Parker del humor\" recorría la geografía americana ofreciendo monólogos erráticos, improvisados y contestatarios que trasladaban en palabras el espíritu libre del bebop. Recogido a menudo en vinilo con un acompañamiento de jazz experimental, el fraseo rapsódico de sus monólogos se construye a partir del reciclaje de fragmentos, la interacción con el público, la imitación de acentos, la autocita y la autodistorsión en un contraste muy marcado con los monologuistas de guión que proliferan hoy. Detenido por las autoridades norteamericanas en numerosas ocasiones bajo la acusación de obscenidad, también consiguió que le prohibieran la entrada para siempre a Inglaterra después de una única actuación. Las palabras y temáticas que tenía prohibido decir en público actúan en sus monólogos como un núcleo atractor: las va circunnavegando hasta que no puede evitar zambullirse en ellas de lleno.",
                "image": "",
                "youtube": "https://www.youtube.com/watch?v=zHaWQy7iEX8&cc_lang_pref=es&cc_load_policy=1",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 26,
                "title": "A Bucket of Blood",
                "author": "Roger Corman",
                "location": "",
                "year": 1959,
                "text": "Uno de los directores por excelencia de la serie B, Roger Corman se especializó en películas de bajo presupuesto rodadas en tres o cuatro días. Las audiencias de los autocines se estremecían ante su particular mezcla de horror inspirado por Poe y sátira social. En la escena escogida, un escultor sin talento mata al gato atrapado detrás de la pared que le está desquiciando con sus maullidos. Después, decidirá recubrir el gato de arcilla y convertirlo en una escultura. Será la pieza que lanzará su carrera hacia el éxito y el reconocimiento crítico. Mucho antes de la calavera de Damien Hirst y los cuerpos de Gunther von Hagens, hubo el gato en la pared de Corman, un extraño símbolo del punto de ruptura: el momento en que un artista que hasta entonces ha vivido en la oscuridad se convierte en un artista reconocido a costa de matar algo invisible y molesto como un maullido.",
                "image": "",
                "youtube": "https://youtu.be/Xa2B2q3NIUY",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 27,
                "title": "Le fantôme de la liberté",
                "author": "Luis Buñuel",
                "location": "",
                "year": 1974,
                "text": "Como el personaje de <em>L’Âge d’Or</em> (1930) que da una patada completamente aleatoria a un perrito, la carrera de Luis Buñuel es una continua y reiterada patada a la exangüe domesticidad de las maneras burguesas. En la misma película vemos como un personaje avanza por la calle chutando un violín. ¿El violín de Ingres del arte entendido como simple pasatiempo para entretenernos? Maestro en gastar bromas pesadas —relata varias con ostensible satisfacción en sus memorias— el arte de Buñel desestabiliza lo convencional desde una mueca de hastío irónico. En esta escena de su penúltima película, la inversión de las actividades que se realizan en espacios públicos y privados nos ofrece un impactante cuestionamiento de lo que entendemos por púdico e impúdico. El elemento más muerto en determinadas sobremesas no es el bistec de carne, sino la putrefacta banalidad de los temas de conversación. La alusión a la sobrepoblación en la escena es quizás un eco o un guiño al panfleto de Swift con que abríamos este recorrido.",
                "image": "",
                "youtube": "",
                "vimeo": "https://vimeo.com/156082721",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            },
            {
                "id": 28,
                "title": "Entre tinieblas",
                "author": "Pedro Almodóvar",
                "location": "",
                "year": 1983,
                "text": "Encajonada entre <em>Laberinto de pasiones</em> y <em>¿Qué he hecho yo para merecer esto?</em>, esta película del director manchego pasó un tanto desapercibida. De hecho, es uno de los momentos álgidos del humor almodovariano: un feroz e irreverente ataque a la doble moral de la Iglesia. La película trata sobre el convento de las \"Redentoras humilladas\", unas monjas que intentan redimir chicas de vida disoluta mientras ellas mismas consumen drogas alucinógenas y establecen relaciones lésbicas. Resulta inquietante preguntarse si esta película podría estrenar-se en la España de hoy, sobre todo a raíz de la inclusión en el Código Penal de 1995 del artículo 525 (delito de ofensa contra el sentimiento religioso). Fue el artículo que se usó para denunciar a Javier Krahe por el corto <em>La Cristofagia o cómo cocinar a un Cristo</em> (1977) después de su emisión por televisión en 2004. El proceso judicial se alargó 8 años, con fianzas cercanas a los 200.000 euros, hasta su absolución en 2012.",
                "image": "",
                "youtube": "https://www.youtube.com/watch?v=6C-nohlmLUQ",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 29,
                "title": "Cuttlas",
                "author": "Calpurnio",
                "location": "",
                "year": "1989-",
                "text": "La tira cómica también conocida como <em>El Bueno de Cuttlass</em> hace décadas que se publica —con algunas interrupciones— en distintos medios como <em>Makoki</em>, <em>El País</em> y <em>20 Minutos</em>. Partiendo del esquema maniqueo de la eterna pugna entre indios y vaqueros, el dibujante zaragozano combate justamente el maniqueísmo de nuestros prejuicios adquiridos. El vaquero protagonista alterna delirante batallas contra los indios con reflexiones existenciales con su amigo mexicano Juan Bala, resguardados del sol del desierto bajo una tapia. Los frecuentes anacronismos permiten que el cómic aborde a menudo temas de actualidad y ridiculice el uso que hacemos de las nuevas tecnologías. Sus historietas se han publicado en Francia, Brasil y Japón, y se han recopilado en nueve volúmenes.",
                "image": "29.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 30,
                "title": "Explotar una mierda",
                "author": "Leo Bassi",
                "location": "",
                "year": 1998,
                "text": "Mostrar la escatofilia genera reacciones de shock y de humor culpable. La escena de la mierda de perro en <em>Pink Flamingos</em> (1972) de John Waters es uno de los momentos más icónicos del cine trash. La mierda representa lo intocable, por eso resulta tan intensa su asociación con conceptos cargados de sublimidad (recordemos el magnífico verso de Gimferrer, inspirado por Yeats: <em>Si l'amor és el lloc de l'excrement</em>). El cómico italiano Leo Bassi ha hecho bandera en su carrera de la irreverencia, la crítica al capitalismo y al obscurantismo. A raíz del estreno de su obra teatral <em>La Revelación</em>, alguien colocó un artefacto explosivo artesanal en el Teatro Alfil de Madrid donde se representaba. Como los antiguos bufones cortesanos, Bassi presenta a menudo una relación simbiótica y ambigua con el poder que representan los medios de masas que critica. Dejamos al espectador la decisión sobre si hay alguna ironía oculta o manifiesta en el hecho que la acción de hacer explotar una mierda se realizara en Telecinco.",
                "image": "",
                "youtube": "https://youtu.be/CQuFdEOE9gM",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 31,
                "title": "Cena de parejas",
                "author": "La Loca de Mierda",
                "location": "",
                "year": 2009,
                "text": "La argentina Malena Pichot empezó en 2008 a publicar una serie de vídeos cortos en Youtube en los cuales atacaba desde el humor algunas de las convenciones sociales más graníticas: la pareja como imposición social, el culto a la procreación, los roles de género y la retórica de la productividad. En otro de sus sketches (<em>Dejar pasar la vida</em>) utiliza compresas que vienen inscritas con píldoras de sabiduría como las galletas de las suerte. Las frases que lee en ellas son una antología irónica del tipo de temáticas que abordan los youtubers más populares: emperifollados consejos de cosmética y frases de autoayuda barata sobre el sentido de la existencia.",
                "image": "",
                "youtube": "https://youtu.be/GlMfLlWkjxY",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 32,
                "title": "Humor negro en las redes sociales",
                "author": "Guillermo Zapata",
                "location": "",
                "year": 2011,
                "text": "Muchos de los chistes que circulan por las redes sociales no tienen autor conocido, son \"reenviados\" o \"compartidos\" hasta que se pierde cualquier traza de autoría. Son humoradas sin humor, bufonadas sin bufón. El autor termina por ser colectivo, el temible <em>Das Man</em> de que hablaba Heidegger. La polémica más reciente sobre este género sí que tuvo autor conocido: estalló en torno a unos tuits del político Guillermo Zapata. En 2015 iba a hacerse cargo de la Concejalía de Cultura y Deportes del Ayuntamiento de Madrid cuando se rescataron del desván de su perfil diversos tuits sobre el holocausto, Irene Villa y las niñas de Alcàsser. En la actualidad está procesado por un delito de humillación a las víctimas del terrorismo por la Audiencia Nacional. La reacción de Irene Villa fue admirable, una muestra de que el humor empieza por contemplarse a uno mismo con ironía, y no por escupir (o retuitear) groseramente los pistones de la sopa de letras que cada día fluye por las redes sociales.",
                "image": "32.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "image"
            }
        ]
    }
];
