var pagesca = [
    {
        "id": 1,
        "code": "001-00A",
        "title": "Page title 1",
        "subtitle": "Page subtitle 1",
        "metatitle": "Riure #1 · Lo Pati",
        "metadescription": "",
        "position": 1,
        "active": true,
        "text": "<h3>Superioritat Vs Inferioritat</h3>Un dels efectes més colpidors de l'acte de riure és el trastocament de les relacions jeràrquiques que provoca. Moltes cultures han establert períodes on les distincions de rang i estatus queden suspeses i l'humor té via lliure per atacar institucions fins aleshores intocables: les saturnals romanes, la festa dels folls medieval i els carnavals són exemples d’aquest momentani capgirament. El caràcter fugisser i fulgurant de la riallada fou intuït per Hobbes en la seva definició d'humor com a “glòria sobtada”: <em>“es pot concloure que l'humor no és sinó la glòria sobtada derivada d’una concepció fugaç d'eminència en nosaltres mateixos, en comparació amb la debilitat dels altres, o amb la nostra pròpia d’abans.”</em><br/><br/>El pas de la riallada privada o canalitzada des del poder a la ganyota revolucionària no és ni molt menys immediat. És enorme la distància que va des del cervantí <em>“debajo de mi manto, al rey mato”</em> a matar el rei amb tota les lletres. Cal admetre que una classe dominant pot esdevenir ridícula molt abans d’esdevenir sobrera en termes històrics. Des de l’escandalosa caricatura de Lluís Felip I convertint-se en una pera fins a la seva abdicació a causa de la Revolució de 1848 passaren disset anys.<br/><br/>Northrop Frye definí la sàtira com a <em>“ironia militant”</em> i és aquest braç armat de l’humor el que pot tenir uns efectes més devastadors en les relacions d’inferioritat/superioritat. En les antigues sagues irlandeses el bard era un soldat més, responsable de llançar ferotges burles sobre l’enemic. Aquestes burles podien arribar a exercir un efecte físic a distància sobre l’objecte del riure (omplint-li, per exemple, el cos de nafres). En els seus orígens mitològics l’humor és confon, doncs, amb la màgia i la maledicció. De fet, en irlandès la paraula “riure” (<em>tibiu</em>) també significa “colpejar”.<br/><br/>L’humor es mou sempre entre dos extrems: la bufonada i la sàtira tràgica. La bufonada es nodreix del cantó ridícul de la natura humana, sovint de la nostra inescapable limitació física: relliscades, tartamudejos, accidents i deformitats. La seva base és degradar l’objecte del riure i fer-nos pensar que, almenys per una vegada, no som nosaltres els qui hem ficat la pota. La sàtira tràgica apunta més amunt i fila prim. És un tipus d’humor que provoca el riure però no participa d’ell perquè l’autor està massa horroritzat per la corrupció generalitzada que l’envolta. <em>“Ira et lacrimae”</em> promet Juvenal als decadents nobles de la Roma imperial en la seva primera sàtira. Karl Kraus, dominador d’aquest gènere al segle XX, afirmà que “si una sàtira es entesa pel censor és que mereix ser censurada”. Tanmateix, no necessariament és la sàtira més elaborada la que acaba tenint una major efectivitat. “El crit d’Iowa”, repetit fins a l’extenuació pels mitjans audiovisuals, posà fi a la carrera del candidat demòcrata Howard Dean.<br/><br/>La repetició està en la base d’un fenomen netament contemporani: la memificació. Etimològicament la paraula “sàtira” està emparentada amb “saturació” i qualsevol usuari de Youtube pot certificar que un fragment curt, descontextualitzat i repetit fins a la saturació exerceix un hipnòtic i infecciós efecte. Es tracta del paroxisme d’una tendència que s’inicià amb la invenció de mitjans de reproducció mecànics com la litografia i la impremta. Aquestes tècniques tragueren l’humor polític dels salons i l’acostaren a les masses sota la forma de caricatures i auques.<br/><br/>En l’humor contemporani s’ha produït el sorgiment de fenòmens nous com el hacktivisme, el <em>defacement</em> de pàgines web o la suplantació de personalitat però el principi subjacent segueix sent la inversió momentània de les relacions de poder i jerarquia. Durant els moments de glòria sobtada d’una riallada entrelluquem un món on les relacions de superioritat/inferioritat han quedat abolides.<br/><br/>Xavier Zambrano.<br/><br/>",
        "summary": "<h3>Superioritat Vs Inferioritat</h3>Un dels efectes més colpidors de l'acte de riure és el trastocament de les relacions jeràrquiques que provoca. Moltes cultures han establert períodes on les distincions de rang i estatus queden suspeses i l'humor té via lliure per atacar institucions fins aleshores intocables: les saturnals romanes, la festa dels folls medieval i els carnavals són exemples d’aquest momentani capgirament. El caràcter fugisser i fulgurant de la riallada fou intuït per Hobbes en la seva definició d'humor com a “glòria sobtada”: <em>“es pot concloure que l'humor no és sinó la glòria sobtada derivada d’una concepció fugaç d'eminència en nosaltres mateixos, en comparació amb la debilitat dels altres, o amb la nostra pròpia d’abans.”</em><br/><br/>Xavier Zambrano.<br/><br/>",
        "medias": [
            {
                "id": 1,
                "title": "Lluís Felip I convertint-se en una pera",
                "author": "Charles Philipon",
                "location": "",
                "year": 1831,
                "text": "Aquest esbós fou dibuixat el 1831 pel caricaturista Charles Philipon davant un tribunal. En el procés s’arriscava a una condemna de 5 anys pels dibuixos que havia publicat a la revista <em>La Caricature</em>. “Tot pot assemblar-se a un rei” — fou el seu al·legat de defensa — “i si condemnem el primer dibuix, també cal condemnar l’últim i tots el dibuixos de peres”. Amb Philipon l’art de la caricatura deixa de rabejar-se en la deformitat dels humils i es converteix en una potent eina de crítica política, la punta de llança de la llibertat de premsa.",
                "image": "1.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 2,
                "title": "Auca dels pelegrins",
                "author": "La Campana de Gràcia",
                "location": "",
                "year": 1891,
                "text": "Les primeres auques tractaven temes força innocus i no es caracteritzaven pel seu humor: inventaris d’arts i oficis, de  jocs d’infantesa o de festes de l’any. Al segle XIX, però, l’ampliació temàtica coincidí amb l’eclosió de la seva popularitat. L’<em>Auca els pelegrins</em> és paradigmàtica del corrent anticlerical i l’agitació social del tombant de segle. Se seguiren usant auques amb finalitats satíriques i propagandistes fins a la Guerra Civil, moment on trobem publicacions com l’<em>Auca del petit burgués que sembla molt i no és res</em>.",
                "image": "2.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "2.png",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega imatge",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 3,
                "title": "Viatge promocional a l'infern",
                "author": "Karl Kraus",
                "location": "",
                "year": 1921,
                "text": "Karl Kraus fou el més gran practicant modern de la sàtira impulsada per la indignació moral davant la corrupció generalitzada. Des de la seva revista <em>Die Fackel</em> fustigà la benpensant societat vienesa d’entreguerres. Intuí amb gran clarividència la capacitat de la publicitat per banalitzar-ho tot, fins i tot l’horror més extrem. A <em>Viatge promocional a l’infern</em> atacà les empreses que organitzaven excursions turístiques als camp de batalla més sanguinaris de la 1ª Guerra Mundial: “Rebreu impressions inoblidables d’un món on no queda ni un centímetre quadrat que no hagi estat destrossat per les granades i els anuncis”.",
                "image": "3.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "3a.pdf",
                "attachment2": "3b.pdf",
                "attachment3": "",
                "textattachmentbutton": "descarrega article alemany",
                "textattachmentbutton2": "descarrega traducció anglès",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 4,
                "title": "Veterans de guerres futures",
                "author": "Estudiants de Princeton",
                "location": "",
                "year": 1936,
                "text": "El 1936 un grup d’estudiants de la Universitat de Princeton, veient molt propera la possibilitat d’una altra guerra mundial, demanaren cobrar per anticipat la pensió que els pertocaria en un futur com a veterans de guerra. D’aquesta manera, podrien gaudir els diners mentre encara eren joves i no haver d’esperar a estar esguerrats per les bombes. Aquesta fina sàtira de la resignació col·lectiva davant el militarisme tingué un gran impacte i esdevingué profètica quan la majoria d’integrants del moviment foren cridats a files.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/JnE9pDPqTKE?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 5,
                "title": "Mon oncle",
                "author": "Jacques Tati",
                "location": "",
                "year": 1958,
                "text": "Jacques Tati bandejà de les seves pel·lícules l’humor tradicional basat en la comicitat dels personatges. El seu és un humor de l’observació: plànols generals sostinguts en el temps que permeten a l’espectador fer-se còmplice del la comicitat del quotidià. Tota situació llargament observada esdevé un gag. A la broma pesada dels nens de <em>Mon oncle</em>, situa la càmera entre els nens, convertint l’espectador en un perpetrador i apuntant a una comicitat molt contemporània: la càmera oculta. El factor repetició anticipa l’humor basat en terrabastades, accidents i bromes pesades de l’era d’Internet.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/pE5vm8vTWCI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 6,
                "title": "El retorn de la columna Durruti",
                "author": "Internacional Situacionista / André Bertrand",
                "location": "",
                "year": 1967,
                "text": "<em>Le Retour de la Colonne Durutti</em> fou un còmic/pamflet repartit entre els estudiants de la Universitat d’Estrasburg. Està construït mitjançat la tècnica del <em>détournement</em>: apropiar-se de mitjans i canals de la societat de l’espectacle, manipular-los i usar-los com a eina de combat contra aquesta mateixa societat. L’obra combina dibuixos, fotogrames, anuncis i fragments de llibres, retocats per obrir-los a nous significats.  L’humor situacionista combina registres dispars, passa de l’ultra-intel·lectualització a la grolleria en una mateixa vinyeta, i reivindica la força del text en una societat que començava a estar saturada d’estímuls visuals.",
                "image": "6.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "6.pdf",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega pamflet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 7,
                "title": "Why I Want to Fuck Ronald Reagan",
                "author": "J.G. Ballard",
                "location": "",
                "year": 1980,
                "text": "A la convenció republicana de 1980, que proclamaria Ronald Reagan com a candidat presidencial, un grup de situacionistes repartí entre els delegats un fullet que contenia un text de J.G. Ballard de 1967. El text estava presentat com si fos un informe intern del propi partit i fins i tot en duia el segell oficial. En la seva demolidora sàtira dels estudis d’opinió, Ballard ataca una política basada en la primacia d’imatges buides. Tanta banalitat era ben capaç de portar al país a escollir un mediocre actor de sèrie B com a president. Ballard va anticipar aquest fet 13 anys abans que es produís, quan Reagan era només governador de Califòrnia, en un text que parodia amb un llenguatge pseudocientífic el masoquisme de les masses de votants.",
                "image": "7.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "7b.jpg",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega fullet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 8,
                "title": "Barbie Liberation Organization",
                "author": "RTMark",
                "location": "",
                "year": 1993,
                "text": "El grup RTMark comprà el 1993 centenars de nines Barbies i ninots G.I. Joe. Intercanviaren les gravacions internes de veu de les dues joguines i les retornaren als estants de les botigues. Les nenes es trobaren, doncs, amb nines Barbies que deien “foc a discreció” i els nens amb G.I. Joes que deien “vull anar de compres”. Aquesta acció contra els estereotips de gènere en els objectes produïts per la societat de consum és de clara inspiració situacionista. El hackeig d’objectes tecnològics esdevé un nou i potent canal per a la sàtira: és el naixement del hacktivisme.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/OPeOD4ZQdXY?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 9,
                "title": "The Yes Men i l’Organització  Mundial de Comerç",
                "author": "The Yes Men",
                "location": "",
                "year": 1999,
                "text": "Començant amb una simple web falsa que volia passar per la de l’Organització Mundial del Comerç, els Yes Men aconseguiren ser convidats com a conferenciants a prestigioses conferències i trobades de sectors neoliberals. Foren entrevistats per canals com la CNBC o la BBC, on expressaren sense embuts opinions com ara que calia electrocutar els treballadors poc productius. Aquesta brillant sàtira de les elits econòmiques i la complicitat amb què compten per part dels mitjans de comunicació situà la suplantació de personalitat com a tècnica humorística contemporània, en una tendència que després seguirien humoristes com Sacha Baron Cohen.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/sW35PKEVYMw?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 10,
                "title": "Una noche con Amenábar",
                "author": "Querido Antonio",
                "location": "",
                "year": 2006,
                "text": "La sàtira d’un personatge públic és un dels gèneres que més memes produeix. L’exposició als mitjans comercials obliga a les personalitats a adoptar una posa i la seva tendència a l’autopromoció els converteix en un blanc ideal per a les sàtires. En aquest vídeo d’Alberto González Vázquez, el director de cinema Amenábar es parodiat en una successió d’escenes plenes d’al·lusions a gèneres fílmics. En la sàtira contemporània el context sovint és visual i un vídeo no s’explica sense molts altres vídeos en una cadena de referencialitats sense fi.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/zH1KxoYp2b4?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 11,
                "title": "El político neoliberal",
                "author": "Pony Bravo",
                "location": "",
                "year": 2013,
                "text": "La inclusió d’un personatge fictici en imatges documentals és una tècnica de gran recorregut humorístic des de <em>Zelig</em> de Woody Allen. Aquest videoclip del grup Pony Bravo no busca l’equívoc (el retoc és volgudament evident) sinó la incongruència i la denúncia d’unes elits que sempre ens ofereixen la cara edulcorada pels mitjans.",
                "image": "",
                "youtube": "",
                "vimeo": "http://player.vimeo.com/video/60601830?title=0&amp;byline=0&amp;portrait=0",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 11,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            }
        ]
    },
    {
        "id": 2,
        "code": "001-00B",
        "title": "Page title 2",
        "subtitle": "Page subtitle 2",
        "metatitle": "Riure #2 · Lo Pati",
        "metadescription": "",
        "position": 2,
        "active": true,
        "text": "<h3>INCONGRUÈNCIA</h3> Segons els partidaris d’aquesta teoria, l’essència de l’humor seria l’incongruent, la confluència en un mateix punt de dues idees o marcs de referència allunyats i dispars. La incongruència humorística llinda per un extrem amb la ironia (quan passat el xoc inicial som capaços de reconciliar les dues idees i adonar-nos que no estaven tan allunyades) i per l’altre amb l’absurd (quan tot intent de reconciliació des de la racionalitat es demostra inútil). Bergson sosté que “una situació és còmica quan pertany simultàniament a dues sèries totalment independents d’esdeveniments i és susceptible de ser interpretada segons dos significats completament diferents al mateix temps”.<br><br>La frustració d’expectatives juga un paper important en el sentiment d’incongruència. Pascal afirma que “res fa riure tant a la gent com una disparitat sorprenent entre el que esperen i el que veuen”. Davant una situació incongruent ens sentim durant uns moments, fins que ens rescata la riallada, víctimes d’un hàbil estafador, com si l’existència se’n rifés de les nostres expectatives més sòlides. Kant situa l’arrencada del riure en el moment quan “una expectativa tensa es dissolt de sobte en el no-res”.<br><br>La imatge incongruent és un híbrid que participa de la natura, curiosa i alhora amenaçadora, de la quimera. La quimera (cap de lleó, cos de cabra i cua de drac) neix en la mitologia grega com a ésser infaust, portador de terribles desgràcies. Aristòtil afirmava que els animals, a diferència dels humans, són incapaços de riure. Les quimeres, en abolir el llindar entre espècies animals, ens plantegen inquietuds pregones sobre les fronteres del nostre propi cos i la línea de separació que distingeix allò humà d’allò animal. L’art grec és aliè als efectes humorístics de la incongruència, però no a la seva potència simbòlica. La figura de l’Hermafrodita i de l’Afroditus o Afrodita masculina fou venerada per cultes mistèrics allunyats de la religió oficial. Els romans també defugien la incongruència i es mostraven més propensos a la sàtira. Horaci advertí que el pintor que posés un cap humà al cos d’un cavall sens dubte provocaria una reacció humorística, però s’hauria de limitar a ensenyar la peça de “manera privada”.<br><br>És en l’era medieval quan la fascinació per les quimeres, gàrgoles i babuins esclata als capitells i a les glosses marginals dels manuscrits en forma d’ il·lustracions escatològiques i obertament sexuals que desestabilitzen des del marge els textos de psalteris i breviaris: es produeix una incongruència entre els discursos profà i sacre, entre el cos del text i la glossa, que remet a la heteroglòssia que Bakhtín detectà com a definitòria d’aquell període.<br><br>Un objecte o situació incongruent se situa sempre en el llindar entre allò humorístic i allò horrible o macabre. Per això les imatges incongruents foren recurrents en els surrealistes. André Breton descriu l’efecte de la imatge surrealista en termes d’incongruència:“la meravellosa facultat de reunir, sense abandonar el reialme de l’experiència, dues realitats molt allunyades i fer saltar l’espurna en posar-les en contacte”.<br><br>Bergson apuntà que una de les situacions humorístiques més freqüents sorgeix quan veiem una persona convertint-se o essent tractada com si fos una cosa. El cinema mut explorà les possibilitats còmiques de la dimensió física del nostre cos fins al punt d’esgotar la combinatòria possible de caigudes i persecucions. Potser la fascinació que ens desperten les imatges i situacions incongruents es degui, com ha apuntat Peter Berger, a una incongruència consubstancial a la nostra pròpia natura, una incongruència “existencial” derivada del fet de ser alhora cossos/coses i persones. ",
        "summary": "<h3>INCONGRUÈNCIA</h3> Segons els partidaris d’aquesta teoria, l’essència de l’humor seria l’incongruent, la confluència en un mateix punt de dues idees o marcs de referència allunyats i dispars. La incongruència humorística llinda per un extrem amb la ironia (quan passat el xoc inicial som capaços de reconciliar les dues idees i adonar-nos que no estaven tan allunyades) i per l’altre amb l’absurd (quan tot intent de reconciliació des de la racionalitat es demostra inútil). Bergson sosté que “una situació és còmica quan pertany simultàniament a dues sèries totalment independents d’esdeveniments i és susceptible de ser interpretada segons dos significats completament diferents al mateix temps”. ",
        "medias": [
            {
                "id": 12,
                "title": "Voeux du paon",
                "author": "Anònim, ca.",
                "location": "Pierpont Morgan Library",
                "year": 1350,
                "text": "L’edat mitjana ha estat sovint presentada com una època on l’obscurantisme feudal i religiós imposava un rictus seriós a totes les manifestacions culturals. Tanmateix, en els marges dels manuscrits i en els capitells de les catedrals es detectable una predilecció molt acusada per la riallada subversiva, per la confrontació i confusió de discursos que pren cos en forma de gàrgoles i quimeres impossibles. La il·luminació dels manuscrits, encarregada habitualment a una persona diferent de l’escriba que fixava el text, era un terreny abonat per a l’esclat incontinent d’aquest gust per la riota: el marge esdevé comentari desestabilitzador de la seriositat oficial, la nota deixa de ser acotació per esdevenir sovint un punxó que obre una via d’aigua per on s’escola la pompositat dels grans discursos monolítics. En aquesta il·lustració al marge d’un romanç que conegué una gran difusió, un home nu es burla de la galant escena cortesana. Més avall, una quimera serpentina tocada amb un mitra fa befa de la religió. Els dos grans discursos idealistes medievals, el cavalleresc i el religiós, són atacats en una mateixa glossa marginal des de la carnalitat i l’animalitat més grollera.",
                "image": "12.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 13,
                "title": "Ressemblances humaines et animales",
                "author": "Charles Le Brun",
                "location": "",
                "year": 1690,
                "text": "És curiós que un dels artífexs del gust neoclàssic en pintura, el pintor i tractadista Charles Le Brun, fos alhora l’autor d’una de les sèries de dibuixos més inquietantment humorístiques de la història de l’art. Compendi que esgota totes les semblances fisonòmiques entre les persones i les bèsties, <em>Ressemblances humaines et animales</em> esdevé un homenatge a la nostra naturalesa híbrida. Deia Aristòtil que l’ésser humà és l’únic animal que riu. Podríem arrodonir la definició afegint-hi que és l’únic animal que s’avergonyeix i amaga les manifestacions de la seva pròpia animalitat. Els dibuixos de Le Brun ens inquieten perquè prenen el camí invers a les faules moralitzants, que humanitzen els animals, i ens remeten a una involució atàvica, una transformació animal explorada per la mitologia grega, en múltiples variants, des que els mariners d’Ulisses foren transformats en porcs.",
                "image": "13final.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 14,
                "title": "Mlle des Faveurs a la Promenade a Londres",
                "author": "Anònim",
                "location": "British Museum",
                "year": "1770-1780",
                "text": "La figura de l’estranger ha estat sempre un agent provocador de situacions incongruents. El xoc entre les habituds i maneres d’un i altre país és font de ridícules incomprensions. Tots els països compten amb acudits ajustats al cèlebre patró de “es troben en un bar un espanyol, un francès i un alemany...”. La llengua anglesa ha fixat aquesta incongruència consubstancial a la condició d’estranger en l’adjectiu <em>“outlandish”</em> (out+land) aplicat sovint a situacions, comentaris i bromes d’una incongruència <em>bizarre</em> . En aquest gravat satíric la <em>coiffure à physionomie élevée</em> que s’estilava a la França cortesana es confosa per un colomar a Anglaterra. La dinàmica del gravat, però, no es limita al xoc de modes, també apunta a un xoc entre el tarannà aristocràtic francès i la mentalitat britànica. La seva data de publicació, pocs anys abans de la Revolució Francesa, és també significativa: una classe social esdevé ridícula abans d’esdevenir sobrera en termes històrics.",
                "image": "14.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 15,
                "title": "Fatty, Mabel and the Law",
                "author": "Mabel Normand",
                "location": "",
                "year": 1912,
                "text": "L’humor de les <em>slapstick comedies</em> del cinema mut es basava en una gestualitat aparatosa, unes persecucions frenètiques i el col·lapse de qualsevol element constructiu que oferís el més mínim punt de suport. Tots aquestes constants posaven en primer pla les penúries que ens ocasiona tenir un cos subjecte —a més de a les seves pròpies lleis— a la llei de la gravetat. Una de les tipologies clàssiques d’aquest gènere són les escenes <em>don’t kiss me</em>. L’actriu còmica Mabel Normand excel·lia en aquest tipus d’escenes físiques, bufetejant sense clemència els homes que provaven de robar-li un petó. La incongruència entre els homes sentimentals, infantils i rodanxons i les iracundes reaccions de la petita Mabel giraven les tornes de les relacions de poder entre sexes i la convertiren en l’antítesi d’altres actrius de cinema mut més ensucrades com Mary Pickford.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/eq-hlPRnS1c?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 16,
                "title": "L.H.O.O.Q.",
                "author": "Marcel Duchamp",
                "location": "",
                "year": 1919,
                "text": "En un dels gestos fundacionals de l’art modern, Duchamp afegí bigoti i pera a una postal de la Gioconda. Titulà l’obra resultant  <em>L.H.O.O.Q.</em>, inicials que pronunciades en francès sonen com <em>“elle a chaud au cul”</em>. Un dels adjectius preferits de Duchamp per desqualificar els moviments que no li agradaven era titllar-los d’avorrits, adjectiu que dedicà per exemple al cubisme. L’humor dadaista cerca la incongruència entre el discurs solemne de l’art oficial, basat en eteris conceptes de sublimitat, i els retocs burletes que desestabilitzen la peça i la posen en un context ordinari. Amb un subtil retoc o un simple canvi de context, el <em>ready-made</em> eleva objectes quotidians a la categoria d’art. En el cas d’aquesta peça, les infinites reproduccions mecàniques en forma de postal s’havien encarregat de degradar la imatge de la Gioconda fins a fer-la ordinària, familiar, massa “avorrida”.",
                "image": "16.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 17,
                "title": "Ministry of Silly Walks",
                "author": "Monty Python",
                "location": "",
                "year": 1970,
                "text": "Emès a la BBC de 1969 a 1977, el programa d’esquetxos <em>Monty Python's Flying Circus</em> revolucionà el format televisiu dels programes d’humor i esbotzà per sempre la concepció tradicional d’allò que s’entenia per “humor anglès”. El caràcter imprevisible del seu humor aconseguia una incongruència radical entre esquetxos: durant el curs d’una emissió se succeïen esquetxos irònics amb d’altres de sarcàstics, escatològics o intel·lectuals. Sovint la incongruència entre formes d’humor es donava dins un mateix esquetx. L’espectador quedava desarmat, incapaç d’anticipar el següent cop. En aquest esquetx, se’ns presenta el Ministeri de maneres absurdes de caminar. Amb referències a la gestualitat del cinema mut, l’esquetx resulta alhora absurd i finament satíric dels delirants requisits governamentals per a la concessió d’ajudes.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/iV2ViNJFZC8?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 18,
                "title": "Ludwig van Beethoven",
                "author": "John Belushi (Saturday Night Live)",
                "location": "",
                "year": 1977,
                "text": "John Belushi, còmic i membre de <em>The Blues Brothers</em>, marcà una fita de l’humor televisiu amb les seves aparicions al programa <em>Saturday Night Live</em> de la NBC entre 1975 i 1979. Els seus salvatges esquetxos en directe popularitzaren el personatge del samurai Futaba, un guerrer oriental que es presentava fora de context, exercint professions tan dispars com grum d’hotel, psiquiatra, reparador de televisors o optometrista. El consum de drogues que ell i el seu company de banda Dan Aykroyd feien als estudis de la cadena abans, durant i després del show esdevingué llegendari i acabà estroncant la seva vida als 33 anys. En aquest esquetx, s’apunta a la transformació de la personalitat mitjançant la intervenció de substàncies: un esllanguit Beethoven es converteix de sobte en Ray Charles. És una transformació amb ressonàncies del Dr. Jekyll i Mr. Hyde i de la incongruència primordial: la convivència no sempre pacífica de múltiples personalitats dins cada persona.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/9YjQ9OmneMI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 19,
                "title": "Tarzan",
                "author": "Rémi Gaillard",
                "location": "",
                "year": 2009,
                "text": "Rémi Gaillard s’ha convertit en el bromista pesat per excel·lència de l’era Youtube. Les seves plagasitats li han reportat milions de seguidors i diverses condemnes judicials. El bromista que estira el fil de la broma fins a les últimes conseqüències és, com els psicòtics, perfectament coherent dins el seu marc referencial. El problema és que el seu marc i la realitat són perfectament incongruents. Així, Gaillard veu un laberint de Pac-Man en els passadissos d’un supermercat o una trinxera militar en les trampes d’arena d’un camp de golf (fent honor a l’origen del seu nom: bunkers). En el vídeo de <em>Tarzan</em> reclama i ocupa un espai perfectament artificial i incongruent, el zoològic urbà. Fer-se incongruent en un espai incongruent no serà tal vegada la més congruent de les accions?",
                "image": "",
                "youtube": "http://www.youtube.com/embed/M-g-etgFk80?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 20,
                "title": "Island of da motherboard slaughter",
                "author": "Gangpol & Mit",
                "location": "",
                "year": 2009,
                "text": "En els últims anys, en el camps de l’animació i el còmic, s’ha produït un corrent estètic que combina la innocència formal més naïf amb el fons temàtic més <em>hardcore</em>. L’efecte d’aquesta incongruència forma/fons pot ésser explotat tant amb finalitats tràgiques com còmiques. El duet gràfic i musical Gangpol & Mit se serveix del <em>pixel-art</em>, les perspectives isomètriques hereves dels videojocs i els sons MIDI per crear estranyes i hipnòtiques animacions que tenen quelcom de tràngol xamànic. Mutilacions, canibalisme i màscares primitives són amorosides per la innocència del píxel i els sons purs dels bips-bips digitals.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/FL5w5pj_5JA?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 21,
                "title": "Drunken politicians",
                "author": "Reactor2studio",
                "location": "",
                "year": 2013,
                "text": "Deia Groucho Marx que la política és l’art de buscar problemes, trobar-los, fer un diagnòstic fals i aplicar els remeis equivocats. Pura incongruència amb les nobles cantarelles del bé comú i el servei públic. Quan un polític es mostra embriac en un context carregat de solemnitat i càlcul racional, com ara un parlament, l’efecte còmic és immediat i infecciós. En un míting, però, l’efecte no és tan fort perquè són ja originàriament cerimònies que busquen l’atordiment dels sentits i l’anul·lació del raciocini, autèntiques borratxeres col·lectives.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/kTy5JaH06zI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 22,
                "title": "A Blobs Bike Ride",
                "author": "Jaimie Warren",
                "location": "",
                "year": 2013,
                "text": "En aquesta peça de l’artista nord-americana Jaimie Warren, una recreació de <em>Le déjeuner sur l'herbe</em> es converteix en una apoteosi del mal gust, en un groller pícnic on els colors pastel competeixen amb els xiscles més estridents i les cançons més insofribles per assolir la incongruència plàstica total. El resultat d’aquesta mena de wagnerianisme invers no pot ser altre que una digestió pesada. Un dels efectes humorístics més sovintejats és fer aflorar les sonoritats i olors de la nostra animalitat en un context extemporani. Així, els pets i els rots en moments inconvenients esdevenen recordatoris que ens avisen que per les nostres entranyes no hi corren només pensaments sublims.",
                "image": "",
                "youtube": "",
                "vimeo": "http://player.vimeo.com/video/68719482?title=0&amp;byline=0&amp;portrait=0",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 11,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            }
        ]
    }
];
