var pagesca = [
    {
        "id": 1,
        "code": "001-00A",
        "title": "Page title 1",
        "subtitle": "Page subtitle 1",
        "metatile": "Riure #1 · Lo Pati",
        "metadescription": "",
        "position": 1,
        "active": true,
        "text": "<h3>Superioritat Vs Inferioritat</h3>Un dels efectes més colpidors de l'acte de riure és el trastocament de les relacions jeràrquiques que provoca. Moltes cultures han establert períodes on les distincions de rang i estatus queden suspeses i l'humor té via lliure per atacar institucions fins aleshores intocables: les saturnals romanes, la festa dels folls medieval i els carnavals són exemples d’aquest momentani capgirament. El caràcter fugisser i fulgurant de la riallada fou intuït per Hobbes en la seva definició d'humor com a “glòria sobtada”: <em>“es pot concloure que l'humor no és sinó la glòria sobtada derivada d’una concepció fugaç d'eminència en nosaltres mateixos, en comparació amb la debilitat dels altres, o amb la nostra pròpia d’abans.”</em><br/><br/>El pas de la riallada privada o canalitzada des del poder a la ganyota revolucionària no és ni molt menys immediat. És enorme la distància que va des del cervantí <em>“debajo de mi manto, al rey mato”</em> a matar el rei amb tota les lletres. Cal admetre que una classe dominant pot esdevenir ridícula molt abans d’esdevenir sobrera en termes històrics. Des de l’escandalosa caricatura de Lluís Felip I convertint-se en una pera fins a la seva abdicació a causa de la Revolució de 1848 passaren disset anys.<br/><br/>Northrop Frye definí la sàtira com a <em>“ironia militant”</em> i és aquest braç armat de l’humor el que pot tenir uns efectes més devastadors en les relacions d’inferioritat/superioritat. En les antigues sagues irlandeses el bard era un soldat més, responsable de llançar ferotges burles sobre l’enemic. Aquestes burles podien arribar a exercir un efecte físic a distància sobre l’objecte del riure (omplint-li, per exemple, el cos de nafres). En els seus orígens mitològics l’humor és confon, doncs, amb la màgia i la maledicció. De fet, en irlandès la paraula “riure” (<em>tibiu</em>) també significa “colpejar”.<br/><br/>L’humor es mou sempre entre dos extrems: la bufonada i la sàtira tràgica. La bufonada es nodreix del cantó ridícul de la natura humana, sovint de la nostra inescapable limitació física: relliscades, tartamudejos, accidents i deformitats. La seva base és degradar l’objecte del riure i fer-nos pensar que, almenys per una vegada, no som nosaltres els qui hem ficat la pota. La sàtira tràgica apunta més amunt i fila prim. És un tipus d’humor que provoca el riure però no participa d’ell perquè l’autor està massa horroritzat per la corrupció generalitzada que l’envolta. <em>“Ira et lacrimae”</em> promet Juvenal als decadents nobles de la Roma imperial en la seva primera sàtira. Karl Kraus, dominador d’aquest gènere al segle XX, afirmà que “si una sàtira es entesa pel censor és que mereix ser censurada”. Tanmateix, no necessariament és la sàtira més elaborada la que acaba tenint una major efectivitat. “El crit d’Iowa”, repetit fins a l’extenuació pels mitjans audiovisuals, posà fi a la carrera del candidat demòcrata Howard Dean.<br/><br/>La repetició està en la base d’un fenomen netament contemporani: la memificació. Etimològicament la paraula “sàtira” està emparentada amb “saturació” i qualsevol usuari de Youtube pot certificar que un fragment curt, descontextualitzat i repetit fins a la saturació exerceix un hipnòtic i infecciós efecte. Es tracta del paroxisme d’una tendència que s’inicià amb la invenció de mitjans de reproducció mecànics com la litografia i la impremta. Aquestes tècniques tragueren l’humor polític dels salons i l’acostaren a les masses sota la forma de caricatures i auques.<br/><br/>En l’humor contemporani s’ha produït el sorgiment de fenòmens nous com el hacktivisme, el <em>defacement</em> de pàgines web o la suplantació de personalitat però el principi subjacent segueix sent la inversió momentània de les relacions de poder i jerarquia. Durant els moments de glòria sobtada d’una riallada entrelluquem un món on les relacions de superioritat/inferioritat han quedat abolides.<br/><br/>Xavier Zambrano.<br/><br/>",
        "summary": "<h3>Superioritat Vs Inferioritat</h3>Un dels efectes més colpidors de l'acte de riure és el trastocament de les relacions jeràrquiques que provoca. Moltes cultures han establert períodes on les distincions de rang i estatus queden suspeses i l'humor té via lliure per atacar institucions fins aleshores intocables: les saturnals romanes, la festa dels folls medieval i els carnavals són exemples d’aquest momentani capgirament. El caràcter fugisser i fulgurant de la riallada fou intuït per Hobbes en la seva definició d'humor com a “glòria sobtada”: <em>“es pot concloure que l'humor no és sinó la glòria sobtada derivada d’una concepció fugaç d'eminència en nosaltres mateixos, en comparació amb la debilitat dels altres, o amb la nostra pròpia d’abans.”</em><br/><br/>Xavier Zambrano.<br/><br/>",
        "medias": [
            {
                "id": 1,
                "title": "Lluís Felip I convertint-se en una pera",
                "author": "Charles Philipon",
                "year": 1831,
                "text": "Aquest esbós fou dibuixat el 1831 pel caricaturista Charles Philipon davant un tribunal. En el procés s’arriscava a una condemna de 5 anys pels dibuixos que havia publicat a la revista <em>La Caricature</em>. “Tot pot assemblar-se a un rei” — fou el seu al·legat de defensa — “i si condemnem el primer dibuix, també cal condemnar l’últim i tots el dibuixos de peres”. Amb Philipon l’art de la caricatura deixa de rabejar-se en la deformitat dels humils i es converteix en una potent eina de crítica política, la punta de llança de la llibertat de premsa.",
                "image": "1.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 2,
                "title": "Auca dels pelegrins",
                "author": "La Campana de Gràcia",
                "year": 1891,
                "text": "Les primeres auques tractaven temes força innocus i no es caracteritzaven pel seu humor: inventaris d’arts i oficis, de  jocs d’infantesa o de festes de l’any. Al segle XIX, però, l’ampliació temàtica coincidí amb l’eclosió de la seva popularitat. L’<em>Auca els pelegrins</em> és paradigmàtica del corrent anticlerical i l’agitació social del tombant de segle. Se seguiren usant auques amb finalitats satíriques i propagandistes fins a la Guerra Civil, moment on trobem publicacions com l’<em>Auca del petit burgués que sembla molt i no és res</em>.",
                "image": "2.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "2.png",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega imatge",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 3,
                "title": "Viatge promocional a l'infern",
                "author": "Karl Kraus",
                "year": 1921,
                "text": "Karl Kraus fou el més gran practicant modern de la sàtira impulsada per la indignació moral davant la corrupció generalitzada. Des de la seva revista <em>Die Fackel</em> fustigà la benpensant societat vienesa d’entreguerres. Intuí amb gran clarividència la capacitat de la publicitat per banalitzar-ho tot, fins i tot l’horror més extrem. A <em>Viatge promocional a l’infern</em> atacà les empreses que organitzaven excursions turístiques als camp de batalla més sanguinaris de la 1ª Guerra Mundial: “Rebreu impressions inoblidables d’un món on no queda ni un centímetre quadrat que no hagi estat destrossat per les granades i els anuncis”.",
                "image": "3.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "3a.pdf",
                "attachment2": "3b.pdf",
                "attachment3": "",
                "textattachmentbutton": "descarrega article alemany",
                "textattachmentbutton2": "descarrega traducció anglès",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 4,
                "title": "Veterans de guerres futures",
                "author": "Estudiants de Princeton",
                "year": 1936,
                "text": "El 1936 un grups d’estudiants de la Universitat de Princeton, veient molt propera la possibilitat d’una altra guerra mundial, demanaren cobrar per anticipat la pensió que els pertocaria en un futur com a veterans de guerra. D’aquesta manera, podrien gaudir els diners mentre encara eren joves i no haver d’esperar a estar esguerrats per les bombes. Aquesta fina sàtira de la resignació col·lectiva davant el militarisme tingué un gran impacte i esdevingué profètica quan la majoria d’integrants del moviment foren cridats a files.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/JnE9pDPqTKE?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 5,
                "title": "Mon oncle",
                "author": "Jacques Tati",
                "year": 1958,
                "text": "Jacques Tati bandejà de les seves pel·lícules l’humor tradicional basat en la comicitat dels personatges. El seu és un humor de l’observació: plànols generals sostinguts en el temps que permeten a l’espectador fer-se còmplice del la comicitat del quotidià. Tota situació llargament observada esdevé un gag. A la broma pesada dels nens de <em>Mon oncle</em>, situa la càmera entre els nens, convertint l’espectador en un perpetrador i apuntant a una comicitat molt contemporània: la càmera oculta. El factor repetició anticipa l’humor basat en terrabastades, accidents i bromes pesades de l’era d’Internet.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/pE5vm8vTWCI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 6,
                "title": "El retorn de la columna Durruti",
                "author": "Internacional Situacionista/ André Bertrand",
                "year": 1967,
                "text": "<em>Le Retour de la Colonne Durutti</em> fou un còmic/pamflet repartit entre els estudiants de la Universitat d’Estrasburg. Està construït mitjançat la tècnica del <em>détournement</em>: apropiar-se de mitjans i canals de la societat de l’espectacle, manipular-los i usar-los com a eina de combat contra aquesta mateixa societat. L’obra combina dibuixos, fotogrames, anuncis i fragments de llibres, retocats per obrir-los a nous significats.  L’humor situacionista combina registres dispars, passa de l’ultra-intel·lectualització a la grolleria en una mateixa vinyeta, i reivindica la força del text en una societat que començava a estar saturada d’estímuls visuals.",
                "image": "6.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "6.pdf",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega pamflet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 7,
                "title": "Why I Want to Fuck Ronald Reagan",
                "author": "J.G. Ballard",
                "year": 1980,
                "text": "A la convenció republicana de 1980, que proclamaria Ronald Reagan com a candidat presidencial, un grup de situacionistes repartí entre els delegats un fullet que contenia un text de J.G. Ballard de 1967. El text estava presentat com si fos un informe intern del propi partit i fins i tot en duia el segell oficial. En la seva demolidora sàtira dels estudis d’opinió, Ballard ataca una política basada en la primacia d’imatges buides. Tanta banalitat era ben capaç de portar al país a escollir un mediocre actor de sèrie B com a president. Ballard va anticipar aquest fet 13 anys abans que es produís, quan Reagan era només governador de Califòrnia, en un text que parodia amb un llenguatge pseudocientífic el masoquisme de les masses de votants.",
                "image": "7.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "7b.jpg",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega fullet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 8,
                "title": "Barbie Liberation Organization",
                "author": "RTMark",
                "year": 1993,
                "text": "El grup RTMark comprà el 1993 centenars de nines Barbies i ninots G.I. Joe. Intercanviaren les gravacions internes de veu de les dues joguines i les retornaren als estants de les botigues. Les nenes es trobaren, doncs, amb nines Barbies que deien “foc a discreció” i els nens amb G.I. Joes que deien “vull anar de compres”. Aquesta acció contra els estereotips de gènere en els objectes produïts per la societat de consum és de clara inspiració situacionista. El hackeig d’objectes tecnològics esdevé un nou i potent canal per a la sàtira: és el naixement del hacktivisme.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/OVT4T7OR3iQ?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 9,
                "title": "The Yes Men i l’Organització  Mundial de Comerç",
                "author": "The Yes Men",
                "year": 1999,
                "text": "Començant amb una simple web falsa que volia passar per la de l’Organització Mundial del Comerç, els Yes Men aconseguiren ser convidats com a conferenciants a prestigioses conferències i trobades de sectors neoliberals. Foren entrevistats per canals com la CNBC o la BBC, on expressaren sense embuts opinions com ara que calia electrocutar els treballadors poc productius. Aquesta brillant sàtira de les elits econòmiques i la complicitat amb què compten per part dels mitjans de comunicació situà la suplantació de personalitat com a tècnica humorística contemporània, en una tendència que després seguirien humoristes com Sacha Baron Cohen.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/sW35PKEVYMw?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 10,
                "title": "Una noche con Amenábar",
                "author": "Querido Antonio",
                "year": 2006,
                "text": "La sàtira d’un personatge públic és un dels gèneres que més memes produeix. L’exposició als mitjans comercials obliga a les personalitats a adoptar una posa i la seva tendència a l’autopromoció els converteix en un blanc ideal per a les sàtires. En aquest vídeo d’Alberto González Vázquez, el director de cinema Amenábar es parodiat en una successió d’escenes plenes d’al·lusions a gèneres fílmics. En la sàtira contemporània el context sovint és visual i un vídeo no s’explica sense molts altres vídeos en una cadena de referencialitats sense fi.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/zH1KxoYp2b4?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 11,
                "title": "El político neoliberal",
                "author": "Pony Bravo",
                "year": 2013,
                "text": "La inclusió d’un personatge fictici en imatges documentals és una tècnica de gran recorregut humorístic des de <em>Zelig</em> de Woody Allen. Aquest videoclip del grup Pony Bravo no busca l’equívoc (el retoc és volgudament evident) sinó la incongruència i la denúncia d’unes elits que sempre ens ofereixen la cara edulcorada pels mitjans.",
                "image": "",
                "youtube": "",
                "vimeo": "http://player.vimeo.com/video/60601830?title=0&amp;byline=0&amp;portrait=0",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 11,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            }
        ]
    },
    {
        "id": 2,
        "code": "001-00B",
        "title": "Page title 2",
        "subtitle": "Page subtitle 2",
        "metatile": "Riure #2 · Lo Pati",
        "metadescription": "",
        "position": 2,
        "active": true,
        "text": "",
        "summary": "",
        "medias": [
            {
                "id": 0,
                "title": "",
                "author": "",
                "year": 0,
                "text": "",
                "image": "",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 0,
                "active": false,
                "type": ""
            }
        ]
    }
];