var pageses = [
    {
        "id": 1,
        "code": "001-00A",
        "title": "Page title 1",
        "subtitle": "Page subtitle 1",
        "metatitle": "Riure #1 · Lo Pati",
        "metadescription": "",
        "position": 1,
        "active": true,
        "text": "<h3>Superioridad Vs Inferioridad</h3>Uno de los efectos más impresionantes del acto de reír es el trastrocamiento de las relaciones jerárquicas que provoca. Muchas culturas han establecido periodos donde las distinciones de rango y estatus quedan suspendidas y el humor tiene vía libre para atacar instituciones hasta entonces intocables: las saturnales romanas, la fiesta de los rabiosos medievales y los carnavales son ejemplos de este momentáneo vuelco. El carácter fugaz y fulgurante de la carcajada fue intuido por Hobbes en su definición de humor como 'gloria súbita': <em>'se puede concluir que el humor no es sino la gloria súbita derivada de una concepción fugaz de eminencia en nosotros mismos, en comparación con la debilidad de los otros, o con nuestra propia de antes.'</em><br/><br/>El paso de la risa privada o canalizada desde el poder a la mueca revolucionaria no es ni mucho menos inmediato. Es enorme la distancia que va desde el cervantino <em>'Debajo de mi manto, al rey mato'</em> a matar el rey con toda las letras. Hay que admitir que una clase dominante puede convertirse ridícula mucho antes de convertirse en superflua en términos históricos. Desde la escandalosa caricatura de Luis Felipe I convirtiéndose en una pera hasta su abdicación debido a la Revolución de 1848 pasaron diecisiete años.<br/><br/>Northrop Frye definió la sátira como <em>'ironía militante'</em> y es este brazo armado del humor lo que puede tener unos efectos más devastadores en las relaciones de inferioridad / superioridad. En las antiguas sagas irlandesas el bardo era un soldado más, responsable de lanzar feroces burlas sobre el enemigo. Estas burlas podían llegar a ejercer un efecto físico a distancia sobre el objeto de la risa (llenándole, por ejemplo, el cuerpo de llagas). En sus orígenes mitológicos del humor es confunde, pues, con la magia y la maldición. De hecho, en irlandés la palabra 'risa' (<em>tibiu</em>) también significa 'golpear'.<br/><br/>El humor se mueve siempre entre dos extremos: la bufonada y la sátira trágica. La bufonada se nutre del lado ridículo de la naturaleza humana, a menudo de nuestra inescapable limitación física: resbalones, tartamudeos, accidentes y deformidades. Su base es degradar el objeto de la risa y hacernos pensar que, al menos por una vez, no somos nosotros los que hemos metido la pata. La sátira trágica apunta más arriba y fila delgado. Es un tipo de humor que provoca la risa pero no participa de él porque el autor está demasiado horrorizado por la corrupción generalizada que le rodea. <em>'Ira te lacrimae'</em> promete Juvenal a los decadentes nobles de la Roma imperial en su primera sátira. Karl Kraus, dominador de este género en el siglo XX, afirmó que 'si una sátira es entendida por el censor es que merece ser censurada'. Sin embargo, no necesariamente es la sátira más elaborada la que acaba teniendo una mayor efectividad. <em>'El grito de Iowa'</em>, repetido hasta la extenuación por los medios audiovisuales, puso fin a la carrera del candidato demócrata Howard Dean.<br/><br/>La repetición está en la base de un fenómeno puramente contemporáneo: la memificación. Etimológicamente la palabra 'sátira' está emparentada con 'saturación' y cualquier usuario de Youtube puede certificar que un fragmento corto, descontextualizado y repetido hasta la saturación ejerce un hipnótico e infeccioso efecto. Se trata del paroxismo de una tendencia que se inició con la invención de medios de reproducción mecánica como la litografía y la imprenta Estas técnicas sacaron el humor político de los salones y la acercaron a las masas bajo la forma de caricaturas y aucas.<br/><br/>En el humor contemporáneo se ha producido el surgimiento de fenómenos nuevos como el hacktivismo, el desasimiento de páginas web o la suplantación de personalidad pero el principio subyacente sigue siendo la inversión momentánea de las relaciones de poder y jerarquía. Durante los momentos de gloria repentina de una carcajada atisban un mundo donde las relaciones de superioridad / inferioridad han quedado abolidas.<br/><br/>Xavier Zambrano.<br/><br/>",
        "summary": "<h3>Superioridad Vs Inferioridad</h3>Uno de los efectos más impresionantes del acto de reír es el trastrocamiento de las relaciones jerárquicas que provoca. Muchas culturas han establecido periodos donde las distinciones de rango y estatus quedan suspendidas y el humor tiene vía libre para atacar instituciones hasta entonces intocables: las saturnales romanas, la fiesta de los rabiosos medievales y los carnavales son ejemplos de este momentáneo vuelco. El carácter fugaz y fulgurante de la carcajada fue intuido por Hobbes en su definición de humor como 'gloria súbita': <em>'se puede concluir que el humor no es sino la gloria súbita derivada de una concepción fugaz de eminencia en nosotros mismos, en comparación con la debilidad de los otros, o con nuestra propia de antes.'</em><br/><br/>Xavier Zambrano.<br/><br/>",
        "medias": [
            {
                "id": 1,
                "title": "Luís Felipe I convirtiéndose en una pera",
                "author": "Charles Philipon",
                "year": 1831,
                "text": "Este boceto fue dibujado en 1831 por el caricaturista Charles Philipon ante un tribunal. En el proceso se arriesgaba a una condena de 5 años por los dibujos que había publicado en la revista <em>La Caricature</em>. 'Todo puede parecerse a un rey' - fue su alegato de defensa - 'y si condenamos el primer dibujo, también hay que condenar el último y todos los dibujos de peras'. Con Philipon el arte de la caricatura deja de cebarse en la deformidad de los humildes y se convierte en una potente herramienta de crítica política, la punta de lanza de la libertad de prensa.",
                "image": "1.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 1,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 2,
                "title": "El Auca de los pelegrinos",
                "author": "La Campana de Gràcia",
                "year": 1891,
                "text": "Las primeras aucas trataban temas bastante inocuos y no se caracterizaban por su humor: inventarios de artes y oficios, de juegos de infancia o de fiestas del año. En el siglo XIX, sin embargo, la ampliación temática coincidió con la eclosión de su popularidad. <em>El Auca de los peregrinos</em> es paradigmática de la corriente anticlerical y la agitación social del cambio de siglo. Se siguieron usando aleluyas con fines satíricos y propagandistas hasta la Guerra Civil, momento donde encontramos publicaciones como <em>El Auca del pequeño burgués que parece mucho y no es nada.</em>.",
                "image": "2.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "2.png",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega imatge",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 2,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 3,
                "title": "Viaje promocional al infierno",
                "author": "Karl Kraus",
                "year": 1921,
                "text": "Karl Kraus fue el más grande practicante moderno de la sátira impulsada por la indignación moral ante la corrupción generalizada. Desde su revista <em>Die Fackel</em> fustigó la bienpensante sociedad vienesa de entreguerras. Intuyó con gran clarividencia la capacidad de la publicidad para banalizarlo todo, incluso el horror más extremo. A <em>Viaje promocional al infierno</em> atacó las empresas que organizaban excursiones turísticas a los campo de batalla más sanguinarios de la 1ª Guerra Mundial: “Recibiréis impresiones inolvidables de un mundo donde no queda ni un centímetro cuadrado que no haya sido destrozado por las granadas y los anuncios”.",
                "image": "3.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "3a.pdf",
                "attachment2": "3b.pdf",
                "attachment3": "",
                "textattachmentbutton": "descarrega article alemany",
                "textattachmentbutton2": "descarrega traducció anglès",
                "textattachmentbutton3": "",
                "position": 3,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 4,
                "title": "Veteranos de guerras futuras",
                "author": "Estudiantes de Princeton",
                "year": 1936,
                "text": "El 1936 un grupo de estudiantes de la Universidad de Princeton, viendo muy cercana la posibilidad de otra guerra mundial, pidieron cobrar por anticipado la pensión que los correspondería en un futuro como veteranos de guerra. De este modo, podrían disfrutar el dinero mientras todavía eran jóvenes y no tener que esperar a estar estropeados por las bombas. Esta fina sátira de la resignación colectiva ante el militarismo tuvo un gran impacto y aconteció profética cuando la mayoría de integrantes del movimiento fueron llamados a filas.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/JnE9pDPqTKE?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 4,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 5,
                "title": "Mon oncle",
                "author": "Jacques Tati",
                "year": 1958,
                "text": "Jacques Tati desterró de sus películas el humor tradicional basado en la comicidad de los personajes. El suyo es un humor de la observación: planos generales sostenidos en el tiempo que permiten al espectador hacerse cómplice del la comicidad del cotidiano. Toda situación largamente observada acontece un gag. A la broma pesada de los niños de <em>Mi tío</em>, sitúa la cámara entre los niños, convirtiendo el espectador en un perpetrador y apuntando a una comicidad muy contemporánea: la cámara oculta. El factor repetición anticipa el humor basado en accidentes y bromas pesadas de la era de Internet.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/pE5vm8vTWCI?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 5,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 6,
                "title": "El regreso de la columna Durruti",
                "author": "Internacional Situacionista / André Bertrand",
                "year": 1967,
                "text": "<em>Le Retour de la Colonne Durutti</em> fue un cómic/panfleto repartido entre los estudiantes de la Universidad de Estrasburgo. Está construido mediante la técnica del détournement: apropiarse de medios y canales de la sociedad del espectáculo, manipularlos y usarlos como herramienta de combate contra esta misma sociedad. La obra combina dibujos, fotogramas, anuncios y fragmentos de libros, retocados para abrirlos a nuevos significados. El humor situacionista combina registros dispares, pasa de la ultra intelectualización a la grosería en una misma viñeta, y reivindica la fuerza del texto en una sociedad que empezaba a estar saturada de estímulos visuales.",
                "image": "6.png",
                "youtube": "",
                "vimeo": "",
                "attachment": "6.pdf",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega pamflet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 6,
                "active": true,
                "isinverted": true,
                "type": "image"
            },
            {
                "id": 7,
                "title": "Why I Want to Fuck Ronald Reagan",
                "author": "J.G. Ballard",
                "year": 1980,
                "text": "A la convención republicana de 1980, que proclamaría Ronald Reagan como candidato presidencial, un grupo de situacionistas repartió entre los delegados un folleto que contenía un texto de J.G. Ballard de 1967. El texto estaba presentado como si fuera un informe interno del propio partido e incluso llevaba el sello oficial. En su demoledora sátira de los estudios de opinión, Ballard ataca una política basada en la primacía de imágenes vacías. Tanta banalidad era muy capaz de traer al país a escoger un mediocre actor de serie B como presidente. Ballard anticipó este hecho 13 años antes de que se produjera, cuando Reagan era sólo gobernador de California, en un texto que parodia con un lenguaje pseudo científico el masoquismo de las masas de votantes.",
                "image": "7.jpg",
                "youtube": "",
                "vimeo": "",
                "attachment": "7b.jpg",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "descarrega fullet complet",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 7,
                "active": true,
                "isinverted": false,
                "type": "image"
            },
            {
                "id": 8,
                "title": "Barbie Liberation Organization",
                "author": "RTMark",
                "year": 1993,
                "text": "El grupo RTMark compró en 1993 centenares de muñecas Barbies y muñecos G.I. Joe. Intercambiaron las grabaciones internas de voz de los dos juguetes y las devolvieron a los estantes de las tiendas. Las niñas se encontraron, pues, con muñecas Barbies que decían “fuego a discreción” y los niños con G.I. Joes que decían “quiero ir de compras”. Esta acción contra los estereotipos de género en los objetos producidos por la sociedad del consumo es de clara inspiración situacionista. El hackeo de objetos tecnológicos acontece un nuevo y potente canal para la sátira: es el nacimiento del hacktivismo.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/OPeOD4ZQdXY?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 8,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 9,
                "title": "The Yes Men y la Organización Mundial de Comercio",
                "author": "The Yes Men",
                "year": 1999,
                "text": "Empezando con una simple web falsa que quería pasar por la de la Organización Mundial del Comercio, los Yes Men consiguieron ser invitados como conferenciantes a prestigiosas conferencias y encuentros de sectores neoliberales. Fueron entrevistados por canales como la CNBC o la BBC, donde expresaron sin tapujos opiniones como por ejemplo que había que electrocutar los trabajadores poco productivos. Esta brillante sátira de las élites económicas y la complicidad con que cuentan por parte de los medios de comunicación situó la suplantación de personalidad como técnica humorística contemporánea, en una tendencia que después seguirían humoristas como Sacha Baron Cohen.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/sW35PKEVYMw?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 9,
                "active": true,
                "isinverted": false,
                "type": "youtube"
            },
            {
                "id": 10,
                "title": "Una noche con Amenábar",
                "author": "Querido Antonio",
                "year": 2006,
                "text": "La sátira de un personaje público es uno de los géneros que más memes produce. La exposición a los medios comerciales obliga a las personalidades a adoptar una pose y su tendencia a la autopromoción los convierte en un blanco ideal para las sátiras. En este vídeo de Alberto González Vázquez, el director de cine Amenábar es parodiado en una sucesión de escenas llenas de alusiones a géneros fílmicos. En la sátira contemporánea el contexto a menudo es visual y un vídeo no se explica sin otros muchos vídeos en una cadena de referencialidades sin fin.",
                "image": "",
                "youtube": "http://www.youtube.com/embed/zH1KxoYp2b4?wmode=transparent",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 10,
                "active": true,
                "isinverted": true,
                "type": "youtube"
            },
            {
                "id": 11,
                "title": "El político neoliberal",
                "author": "Pony Bravo",
                "year": 2013,
                "text": "La inclusión de un personaje ficticio en imágenes documentales es una técnica de gran recorrido humorístico desde <em>Zelig</em> de Woody Allen. Este videoclip del grupo Pony Bravo no busca el equívoco (el retoque es deliberadamente evidente) sino la incongruencia y la denuncia de unas élites que siempre nos ofrecen la cara edulcorada por los medios.",
                "image": "",
                "youtube": "",
                "vimeo": "http://player.vimeo.com/video/60601830?title=0&amp;byline=0&amp;portrait=0",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 11,
                "active": true,
                "isinverted": false,
                "type": "vimeo"
            }
        ]
    },
    {
        "id": 2,
        "code": "001-00B",
        "title": "Page title 2",
        "subtitle": "Page subtitle 2",
        "metatitle": "Riure #2 · Lo Pati",
        "metadescription": "",
        "position": 2,
        "active": true,
        "text": "",
        "summary": "",
        "medias": [
            {
                "id": 0,
                "title": "",
                "author": "",
                "year": 0,
                "text": "",
                "image": "",
                "youtube": "",
                "vimeo": "",
                "attachment": "",
                "attachment2": "",
                "attachment3": "",
                "textattachmentbutton": "",
                "textattachmentbutton2": "",
                "textattachmentbutton3": "",
                "position": 0,
                "active": false,
                "type": ""
            }
        ]
    }
];